//! Snapshot of the hosted capability catalog for the public docs.
//!
//! Decision: the docs catalog (`docs/capabilities/index.md`) used to be
//! hand-written and drifted from the registry. This test writes the registry
//! the server serves (`oss_capability_registry_for_grade`, the same call
//! `crates/server/src/platform.rs` makes) to `docs/api/capability-catalog.json`
//! and fails when the committed file differs. `scripts/test-docs-catalogs.sh`
//! then checks the docs pages against that file without compiling Rust, so a
//! docs-only edit is checked too.
//!
//! The registry is composed with the `everruns-platform` features the server
//! enables (see this crate's dev-dependencies); the shell check keeps the two
//! feature lists equal.
//!
//! Regenerate with:
//! `UPDATE_DOCS_CATALOG=1 cargo test -p everruns-integrations-catalog docs_catalog`

use std::collections::BTreeMap;
use std::path::PathBuf;

use everruns_core::capabilities::Capability;
use everruns_core::capability_types::CapabilityStatus;
use everruns_core::{CapabilityInfo, DeploymentGrade};
use serde_json::{Value, json};

use crate::{capability_plugins, oss_capability_registry_for_grade};

fn snapshot_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../docs/api/capability-catalog.json")
}

fn status_name(status: &CapabilityStatus) -> String {
    serde_json::to_value(status)
        .ok()
        .and_then(|value| value.as_str().map(str::to_string))
        .unwrap_or_else(|| format!("{status:?}"))
}

fn describe(capability: &dyn Capability) -> Value {
    let info = CapabilityInfo::from_core(capability);
    let mut tools: Vec<String> = info
        .tool_definitions
        .iter()
        .map(|tool| tool.name().to_string())
        .collect();
    tools.sort();
    json!({
        "id": info.id.to_string(),
        "name": info.name,
        "category": info.category,
        "status": status_name(&info.status),
        "grades": [],
        "feature_flag": everruns_platform::FeatureFlags::required_for_capability(capability.id()),
        "tools": tools,
        "dependencies": info.dependencies,
        "features": info.features,
        "docs_slug": info.docs_slug,
    })
}

/// Registry contents per grade, keyed by capability id.
///
/// `grades` lists the deployment grades that register the capability with no
/// `FEATURE_*` overrides. Integration plugins behind a deployment flag are not
/// registered by default at any grade; they are added with the grades their
/// rollout grade permits and the flag in `feature_flag`. Hosted
/// capabilities gated by an internal flag in code (`session_sandbox`, `lua`)
/// are not plugins and stay out of the snapshot.
fn catalog() -> Value {
    let mut entries: BTreeMap<String, Value> = BTreeMap::new();
    for (grade, grade_name) in [
        (DeploymentGrade::Prod, "prod"),
        (DeploymentGrade::Dev, "dev"),
    ] {
        let registry = oss_capability_registry_for_grade(grade);
        for capability in registry.list() {
            let entry = entries
                .entry(capability.id().to_string())
                .or_insert_with(|| describe(capability.as_ref()));
            entry["grades"]
                .as_array_mut()
                .expect("grades is an array")
                .push(json!(grade_name));
        }
    }
    let flagged = capability_plugins()
        .chain(everruns_platform::container_sandbox::CAPABILITY_PLUGINS.iter())
        .filter_map(|plugin| plugin.feature_flag.map(|flag| (plugin, flag)));
    for (plugin, flag) in flagged {
        let capability = (plugin.factory)();
        let entry = entries
            .entry(capability.id().to_string())
            .or_insert_with(|| describe(capability.as_ref()));
        entry["feature_flag"] = json!(flag);
        // Explicit rollout promotion overrides experimental-only metadata.
        entry["grades"] = json!(["prod", "dev"]);
    }
    json!({
        "_comment": "Generated by crates/integrations-catalog/src/docs_catalog.rs. Do not edit by hand.",
        "capabilities": entries.into_values().collect::<Vec<_>>(),
    })
}

/// Env vars that change what the registry registers. With any of them set the
/// registry no longer reflects the default deployment, so the comparison is
/// skipped rather than reported as drift.
fn registry_overridden_by_env() -> Option<String> {
    std::env::vars()
        .map(|(key, _)| key)
        .find(|key| key.starts_with("FEATURE_"))
}

#[test]
fn docs_capability_catalog_matches_registry() {
    if let Some(key) = registry_overridden_by_env() {
        eprintln!("skipping docs capability catalog check: {key} changes the registry");
        return;
    }
    let mut rendered = serde_json::to_string_pretty(&catalog()).expect("catalog serializes");
    rendered.push('\n');
    let path = snapshot_path();
    if std::env::var_os("UPDATE_DOCS_CATALOG").is_some() {
        std::fs::write(&path, &rendered).expect("write docs capability catalog");
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert!(
        committed == rendered,
        "docs/api/capability-catalog.json is out of date with the capability registry.\n\
         Regenerate it with:\n  \
         UPDATE_DOCS_CATALOG=1 cargo test -p everruns-integrations-catalog docs_catalog\n\
         then run scripts/test-docs-catalogs.sh and update docs/capabilities/ to match."
    );
}
