-- Generic Queue: make workflow_id nullable so tasks can be enqueued standalone
-- (without a parent workflow). Enables fire-and-forget queue semantics on top
-- of existing durable infrastructure (SKIP LOCKED, retry, DLQ, monitoring).

-- Task queue: allow standalone tasks (no workflow)
ALTER TABLE durable_task_queue
    ALTER COLUMN workflow_id DROP NOT NULL;

-- DLQ: allow standalone tasks (no workflow)
ALTER TABLE durable_dead_letter_queue
    ALTER COLUMN workflow_id DROP NOT NULL;

-- Drop the existing FK so we can re-add it with the correct nullable semantics.
-- The FK name was auto-generated by the original CREATE TABLE. Use the canonical name.
ALTER TABLE durable_dead_letter_queue
    DROP CONSTRAINT IF EXISTS durable_dead_letter_queue_workflow_id_fkey;

-- Re-add FK: only validated when workflow_id IS NOT NULL (implicit; NULLs pass FK checks)
ALTER TABLE durable_dead_letter_queue
    ADD CONSTRAINT durable_dead_letter_queue_workflow_id_fkey
    FOREIGN KEY (workflow_id) REFERENCES durable_workflow_instances(id) ON DELETE CASCADE;

-- Index for finding standalone tasks (NULL workflow_id)
CREATE INDEX idx_durable_task_queue_standalone
    ON durable_task_queue(created_at DESC)
    WHERE workflow_id IS NULL;
