// HTTP API routes
//
// This module contains all HTTP route handlers for the public API.
// Each submodule handles a specific resource type with its own AppState.

pub mod a2a_signing;
pub mod ag_ui;
pub mod agent_credentials;
pub mod agent_examples;
pub mod agent_identities;
pub mod agent_identity_connections;
pub mod agent_triggers;
pub mod agents;
pub mod app_a2a;
pub mod app_api;
pub mod app_endpoint_auth;
pub mod app_webhooks;
pub mod apps;
pub mod audit_logs;
pub mod budgets;
pub mod capabilities;
pub mod channel_rate_limit;
pub mod commands;
pub mod common;
pub mod dispatch;
pub mod durable;
pub mod evals;
pub mod events;
pub mod fcp;
pub mod feature_flags;
pub mod harness_examples;
pub mod harnesses;
pub mod http_signing_keys;
pub mod images;
pub mod internal_images;
pub mod knowledge_bases;
pub mod knowledge_indexes;
pub mod mcp_elicitation;
pub mod mcp_endpoint;
pub mod mcp_servers;
pub mod mcp_url_consent;
pub mod memory;
pub mod memory_files;
pub mod messages;
pub mod models;
pub mod notifications;
pub mod observers;
pub mod org_feature_flags;
pub mod org_invitations;
pub mod organizations;
pub mod payments;
pub mod plugins;
pub mod prometheus;
pub mod prometheus_recorder;
pub mod providers;
pub mod public;
pub mod public_chat;
pub mod reporting;
pub mod resolver;
pub mod schedules;
pub mod session_databases;
pub mod session_files;
pub mod session_git;
pub mod session_resources;
pub mod session_sandbox;
pub mod session_schedules;
pub mod session_storage;
pub mod session_tasks;
pub mod sessions;
pub mod skills;
pub mod slack_events;
pub mod sse;
pub mod task_webhooks;
pub mod tool_results;
pub mod turnstile;
pub mod user_connections;
pub mod user_preferences;
pub mod users;
pub mod validation;
pub mod voice;
pub mod workspace_files;
pub mod workspaces;

// Re-export common types
pub use common::{ErrorResponse, ListResponse, PaginatedResponse};
