//! PACT Delegated profile configuration (PACT 1.0 §5) for an A2A endpoint's
//! PACT profile. Holds only public data: URLs, issuers, public keys and the
//! permissions ("scopes") the company offers. The keys that sign delegation
//! tokens are generated by the server and never appear here.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Lets a personal agent act on the user's account with the company behind
/// the endpoint. The user signs in on the company's own login page, approves
/// some of the scopes below on an Everruns consent page, and the personal
/// agent gets a delegation token listing them (OAuth 2.0 device code).
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, PartialEq)]
pub struct PactDelegationConfig {
    /// Company name shown on the consent page. Defaults to the agent's name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    /// The company's login page (HTTPS). The user is sent here with a
    /// `return_to` parameter naming the Everruns consent page; after signing
    /// the user in, the company's site POSTs a signed `assertion` there.
    pub login_url: String,
    /// Exact `iss` of the company's sign-in assertions.
    pub login_issuer: String,
    /// HTTPS URL of the JWKS the company signs assertions with. Set this or
    /// `login_jwks`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub login_jwks_uri: Option<String>,
    /// The company's assertion keys inline, as a JWKS document. Set this or
    /// `login_jwks_uri`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(value_type = Option<Object>)]
    pub login_jwks: Option<serde_json::Value>,
    /// Where the user lands after approving or denying (HTTPS), with
    /// `status=approved|denied`, `scope` and `client` added to its query.
    /// Without it, Everruns shows its own "return to your agent" page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub connected_url: Option<String>,
    /// Name of the org's catalog MCP server for the company's own API. The
    /// agent attaches it as a preset with `actsAs: user`; during a turn sent
    /// with a delegation token, that token is the attachment's bearer, so
    /// the API acts for that user only. Without it, tokens still gate the
    /// tools listed under `scopes`, but nothing calls the company as the user.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mcp_server: Option<String>,
    /// Permissions the user can grant, listed on the Agent Card.
    pub scopes: Vec<PactScope>,
}

/// One permission a user can grant (§5.2).
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, PartialEq)]
pub struct PactScope {
    /// Scope id, e.g. `orders:read`. Printable ASCII without spaces, quotes or
    /// backslashes (RFC 6749 §3.3).
    pub id: String,
    /// Shown verbatim to the user on the consent page and listed on the card.
    pub description: String,
    /// Agent tools that need this scope, by the name the model calls them
    /// (an MCP tool is `mcp_{server}__{tool}`). A turn that calls one without
    /// the scope granted answers with a step-up request instead of a reply.
    /// Tools no scope lists stay available to every personal agent.
    #[serde(default)]
    pub tools: Vec<String>,
}

impl PactDelegationConfig {
    /// The scope with this id, if the company offers it.
    pub fn scope(&self, id: &str) -> Option<&PactScope> {
        self.scopes.iter().find(|scope| scope.id == id)
    }

    /// Ids of the scopes that list `tool`.
    pub fn scopes_for_tool(&self, tool: &str) -> impl Iterator<Item = &str> {
        self.scopes
            .iter()
            .filter(move |scope| scope.tools.iter().any(|listed| listed == tool))
            .map(|scope| scope.id.as_str())
    }
}
