//! Personal Agent Protocol ("Poppy", draft 0.1, <https://personalagentprotocol.org>)
//! channel configuration: a company's front door for personal agents, served
//! by Everruns at `/v1/channels/{channel_id}/poppy`. The company redirects its
//! own `/.well-known/poppy.json` here.
//!
//! Holds only public data: domains, names and personal-agent client ids. The
//! key that signs session tokens is generated by the server and never appears
//! here. See `knowledge/integrations/poppy-channel.md`.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// Longest list of company domains or personal agents a channel may hold.
pub const MAX_POPPY_LIST: usize = 50;

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, PartialEq, Default)]
pub struct PoppyChannelConfig {
    /// Company name in `poppy.json` (`organization.name`). Defaults to the
    /// agent's name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub organization_name: Option<String>,
    /// The company's domains, lowercase host names such as `example.com`.
    /// Each one redirects its `/.well-known/poppy.json` to this channel. The
    /// first is the one `poppy.json` names; all of them are listed as
    /// `poppy_domains` in the sign-in server's metadata.
    pub domains: Vec<String>,
    /// Personal agents allowed to start sessions, by `client_id` (the HTTPS
    /// URL of their client metadata document). Absent means any personal
    /// agent that proves its identity.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allowed_agents: Option<Vec<String>>,
    /// Personal agents refused even when `allowed_agents` is absent.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub blocked_agents: Vec<String>,
    /// Optional per-IP rate limit for this channel, in requests per minute.
    /// `None` or `Some(0)` leaves only the global API limit.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_limit_per_minute: Option<u32>,
}

impl PoppyChannelConfig {
    /// Whether the channel accepts sessions from `client_id`.
    pub fn admits(&self, client_id: &str) -> bool {
        !self
            .blocked_agents
            .iter()
            .any(|blocked| blocked == client_id)
            && self
                .allowed_agents
                .as_ref()
                .is_none_or(|allowed| allowed.iter().any(|agent| agent == client_id))
    }

    /// The problem with this config, if any.
    pub fn validate(&self) -> Result<(), String> {
        if let Some(name) = &self.organization_name
            && (name.trim().is_empty() || name.chars().count() > 200)
        {
            return Err("organization_name must be 1 to 200 characters".into());
        }
        if self.domains.is_empty() {
            return Err("domains must name at least one company domain".into());
        }
        if self.domains.len() > MAX_POPPY_LIST {
            return Err(format!("domains holds at most {MAX_POPPY_LIST} entries"));
        }
        for domain in &self.domains {
            if !is_host_name(domain) {
                return Err(format!(
                    "domain {domain:?} must be a lowercase host name such as example.com"
                ));
            }
        }
        let agents = self.allowed_agents.iter().flatten();
        for (count, agent) in agents.chain(&self.blocked_agents).enumerate() {
            if count >= 2 * MAX_POPPY_LIST {
                return Err(format!(
                    "allowed_agents and blocked_agents hold at most {MAX_POPPY_LIST} entries each"
                ));
            }
            if !is_client_id(agent) {
                return Err(format!(
                    "personal agent {agent:?} must be the HTTPS URL of its client metadata document"
                ));
            }
        }
        if self
            .rate_limit_per_minute
            .is_some_and(|limit| limit > 1_000_000)
        {
            return Err("rate_limit_per_minute must be at most 1,000,000".into());
        }
        Ok(())
    }
}

/// A DNS host name with at least two labels, lowercase, no port or scheme.
fn is_host_name(value: &str) -> bool {
    let labels: Vec<&str> = value.split('.').collect();
    value.len() <= 253
        && labels.len() >= 2
        && labels.iter().all(|label| {
            !label.is_empty()
                && label.len() <= 63
                && !label.starts_with('-')
                && !label.ends_with('-')
                && label
                    .bytes()
                    .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
        })
}

/// An HTTPS URL with a host and no fragment (OAuth Client ID Metadata
/// Document).
fn is_client_id(value: &str) -> bool {
    url::Url::parse(value).is_ok_and(|url| {
        url.scheme() == "https"
            && url.host_str().is_some()
            && url.fragment().is_none()
            && url.username().is_empty()
            && url.password().is_none()
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config() -> PoppyChannelConfig {
        PoppyChannelConfig {
            domains: vec!["example.com".into()],
            ..Default::default()
        }
    }

    #[test]
    fn admits_any_agent_unless_listed_or_blocked() {
        let mut config = config();
        assert!(config.admits("https://pa.example/agent.json"));
        config.blocked_agents = vec!["https://pa.example/agent.json".into()];
        assert!(!config.admits("https://pa.example/agent.json"));
        config.blocked_agents.clear();
        config.allowed_agents = Some(vec!["https://other.example/agent.json".into()]);
        assert!(!config.admits("https://pa.example/agent.json"));
        assert!(config.admits("https://other.example/agent.json"));
    }

    #[test]
    fn validates_domains_and_agents() {
        assert!(config().validate().is_ok());
        for domain in ["", "Example.com", "https://example.com", "example", "a..b"] {
            let config = PoppyChannelConfig {
                domains: vec![domain.into()],
                ..Default::default()
            };
            assert!(config.validate().is_err(), "{domain}");
        }
        assert!(PoppyChannelConfig::default().validate().is_err());
        let mut bad_agent = config();
        bad_agent.allowed_agents = Some(vec!["http://pa.example/agent.json".into()]);
        assert!(bad_agent.validate().is_err());
    }
}
