version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/crates/server"
      - "/crates/worker"
      - "/apps/ui"
      - "/docker"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "npm"
    directories:
      - "/apps/ui"
      - "/apps/docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
