// Event service for business logic
//
// Events are SSE notifications following the standard event protocol.
// This service is the central entry point for event ingestion from both
// HTTP API and gRPC service.
//
// Decision: Ephemeral events (deltas, LLM generation) skip PostgreSQL
// entirely and flow only through EventDelivery (NATS / in-memory).
// Durable events are stored in PG AND published to EventDelivery.
// SSE streams subscribe to EventDelivery instead of polling PG.
//
// IMPORTANT: Event IDs are ALWAYS generated by the database (uuidv7())
// for durable events. Ephemeral events get a locally-generated ID.
//
// Event Listeners:
// After persisting events, the service notifies registered listeners for
// observability integrations (OTel spans, metrics, etc.). Listeners are
// called synchronously but should be non-blocking.

use crate::event_delivery::EventDelivery;
use crate::storage::{EventRow, StorageBackend, models::CreateEventRow};
use anyhow::{Result, bail};
use everruns_core::typed_id::{EventId, SessionId};
use everruns_core::{Event, EventListener, EventRequest};
use std::sync::Arc;
use uuid::Uuid;

#[derive(Clone)]
pub struct EventService {
    db: Arc<StorageBackend>,
    /// Real-time event delivery (NATS / in-memory) for SSE push
    event_delivery: EventDelivery,
    /// Registered event listeners for observability
    listeners: Arc<Vec<Arc<dyn EventListener>>>,
}

impl EventService {
    pub fn new(db: Arc<StorageBackend>, event_delivery: EventDelivery) -> Self {
        Self {
            db,
            event_delivery,
            listeners: Arc::new(Vec::new()),
        }
    }

    /// Create an EventService with registered listeners
    pub fn with_listeners(
        db: Arc<StorageBackend>,
        event_delivery: EventDelivery,
        listeners: Vec<Arc<dyn EventListener>>,
    ) -> Self {
        Self {
            db,
            event_delivery,
            listeners: Arc::new(listeners),
        }
    }

    /// Get reference to the event delivery backend (for SSE subscriptions).
    pub fn event_delivery(&self) -> &EventDelivery {
        &self.event_delivery
    }

    /// Notify all registered listeners about an event.
    ///
    /// Each listener is called in isolation - if a listener panics or fails,
    /// other listeners are still notified. This ensures misbehaving listeners
    /// cannot disrupt event processing.
    async fn notify_listeners(&self, event: &Event) {
        for listener in self.listeners.iter() {
            // Check if listener wants this event type
            let should_notify = listener
                .event_types()
                .map(|types| types.contains(&event.event_type.as_str()))
                .unwrap_or(true); // None means all events

            if should_notify {
                let listener_name = listener.name();
                let listener = listener.clone();
                let event = event.clone();

                // Spawn listener in isolated task to catch panics
                let handle = tokio::spawn(async move {
                    listener.on_event(&event).await;
                });

                // Wait for completion, log but don't propagate panics
                if let Err(e) = handle.await {
                    tracing::error!(
                        listener = listener_name,
                        error = %e,
                        "EventListener panicked or was cancelled"
                    );
                }
            }
        }
    }

    /// Validate that event_type matches the data type.
    /// Unsupported events are rejected - they should not be emitted via this service.
    fn validate_event_type_consistency(request: &EventRequest) -> Result<()> {
        // Reject unsupported events - they should never be created, only encountered during read
        if request.data.is_unsupported() {
            bail!("cannot emit unsupported event type");
        }

        let data_event_type = request.data.event_type();

        // Validate consistency between declared type and data type
        if request.event_type != data_event_type {
            bail!(
                "event type mismatch: declared '{}' but data indicates '{}'",
                request.event_type,
                data_event_type
            );
        }

        Ok(())
    }

    /// Emit a typed event request.
    ///
    /// Routing:
    /// - **Ephemeral** events (deltas, LLM generation) when NATS is active:
    ///   published to EventDelivery only. No PG write, no sequence allocation.
    /// - **All events** when NATS is not active (InMemory mode): stored in PG
    ///   as before. No behavioral change without explicit NATS opt-in.
    /// - **Durable** events: always stored in PG + published to EventDelivery.
    ///
    /// All registered listeners are notified regardless of durability.
    ///
    /// # Errors
    /// Returns an error if event_type doesn't match the data type.
    pub async fn emit(&self, request: EventRequest) -> Result<Event> {
        Self::validate_event_type_consistency(&request)?;

        // Only skip PG for ephemeral events when the delivery backend supports it
        // (NATS provides durable pub/sub with replay). InMemory mode persists
        // everything to PG — zero behavioral change without NATS_URL.
        if request.is_ephemeral() && self.event_delivery.supports_ephemeral_skip() {
            return self.emit_ephemeral(request).await;
        }

        self.emit_durable(request).await
    }

    /// Emit an ephemeral event (skip PG, deliver via EventDelivery only).
    async fn emit_ephemeral(&self, request: EventRequest) -> Result<Event> {
        tracing::debug!(
            session_id = %request.session_id,
            event_type = %request.event_type,
            "EventService: ephemeral event (skipping PG)"
        );

        // Create a synthetic Event with locally-generated ID, no PG sequence
        let event = Event {
            id: EventId::new(),
            event_type: request.event_type,
            ts: request.ts,
            session_id: request.session_id,
            context: request.context,
            data: request.data,
            metadata: request.metadata,
            tags: request.tags,
            sequence: None,
        };

        // Publish to EventDelivery for SSE subscribers
        if let Err(e) = self.event_delivery.publish(&event).await {
            tracing::warn!(
                error = %e,
                event_type = %event.event_type,
                "Failed to publish ephemeral event to delivery backend"
            );
        }

        // Notify listeners (OTel, metrics) even for ephemeral events
        self.notify_listeners(&event).await;

        Ok(event)
    }

    /// Emit a durable event (store in PG + publish to EventDelivery).
    async fn emit_durable(&self, request: EventRequest) -> Result<Event> {
        let create_row = CreateEventRow {
            session_id: request.session_id,
            event_type: request.event_type,
            ts: request.ts,
            context: serde_json::to_value(&request.context)?,
            data: serde_json::to_value(&request.data)?,
            metadata: request.metadata,
            tags: request.tags,
        };

        let row = self.db.create_event(create_row).await?;
        let event = Self::row_to_event(row);

        // Publish to EventDelivery for SSE subscribers
        if let Err(e) = self.event_delivery.publish(&event).await {
            tracing::warn!(
                error = %e,
                event_type = %event.event_type,
                "Failed to publish durable event to delivery backend"
            );
        }

        // Notify listeners after persisting
        self.notify_listeners(&event).await;

        Ok(event)
    }

    /// Emit a batch of typed event requests.
    /// Ephemeral events skip PG only when NATS is active; otherwise all go to PG.
    /// Returns the count of successfully processed events.
    ///
    /// # Errors
    /// Returns an error if any event_type doesn't match the data type.
    pub async fn emit_batch(&self, requests: Vec<EventRequest>) -> Result<i32> {
        // Validate all requests first to fail fast
        for request in &requests {
            Self::validate_event_type_consistency(request)?;
        }

        let skip_ephemeral = self.event_delivery.supports_ephemeral_skip();
        let mut count = 0i32;

        for request in requests {
            if request.is_ephemeral() && skip_ephemeral {
                self.emit_ephemeral(request).await?;
            } else {
                self.emit_durable(request).await?;
            }
            count += 1;
        }

        Ok(count)
    }

    /// Create an event from raw row data
    pub async fn create(&self, input: CreateEventRow) -> Result<Event> {
        let row = self.db.create_event(input).await?;
        let event = Self::row_to_event(row);

        // Notify listeners after persisting
        self.notify_listeners(&event).await;

        Ok(event)
    }

    /// List events for a session, filtering out unsupported events.
    /// Unsupported events are internal and never exposed via API.
    /// `filter_types`: positive filter — when non-empty, only return matching types.
    /// `exclude_types`: negative filter — remove matching types from the result.
    /// When both are provided, `filter_types` narrows first, then `exclude_types` removes.
    /// `before_sequence`: cursor for backward pagination (events before this sequence).
    /// `limit`: max number of events to return (backward pagination, last N events).
    #[allow(clippy::too_many_arguments)]
    pub async fn list(
        &self,
        session_id: Uuid,
        since_sequence: Option<i32>,
        since_id: Option<Uuid>,
        filter_types: &[String],
        exclude_types: &[String],
        before_sequence: Option<i32>,
        limit: Option<i32>,
    ) -> Result<Vec<Event>> {
        let rows = self
            .db
            .list_events(
                SessionId::from_uuid(session_id),
                since_sequence,
                since_id.map(EventId::from_uuid),
                filter_types,
                exclude_types,
                before_sequence,
                limit,
            )
            .await?;
        Ok(rows
            .into_iter()
            .map(Self::row_to_event)
            .filter(|e| !e.is_unsupported())
            .collect())
    }

    /// Count events for a session, excluding specified types (for X-Total-Count header).
    pub async fn count_events(&self, session_id: Uuid, exclude_types: &[String]) -> Result<i64> {
        self.db
            .count_events(SessionId::from_uuid(session_id), exclude_types)
            .await
    }

    /// Find the nearest turn.started sequence at or before the given sequence.
    /// Used for turn boundary snapping in pagination.
    pub async fn find_turn_boundary(
        &self,
        session_id: Uuid,
        before_sequence: i32,
    ) -> Result<Option<i32>> {
        self.db
            .find_turn_boundary(SessionId::from_uuid(session_id), before_sequence)
            .await
    }

    /// List events that represent messages (user, agent, tool results)
    /// Used by gRPC service to load conversation history for workers.
    /// Filters out unsupported events.
    pub async fn list_message_events(&self, session_id: Uuid) -> Result<Vec<Event>> {
        self.list_message_events_limited(session_id, None).await
    }

    /// List message events with an optional limit on count.
    /// Returns most recent N messages in sequence order when limit is provided.
    pub async fn list_message_events_limited(
        &self,
        session_id: Uuid,
        limit: Option<i32>,
    ) -> Result<Vec<Event>> {
        let rows = self
            .db
            .list_message_events_limited(SessionId::from_uuid(session_id), limit)
            .await?;
        Ok(rows
            .into_iter()
            .map(Self::row_to_event)
            .filter(|e| !e.is_unsupported())
            .collect())
    }

    fn row_to_event(row: EventRow) -> Event {
        // Direct mapping from row columns to Event fields
        // Use the core library's deserialize_event_data for proper type handling
        let data = everruns_core::events::deserialize_event_data(&row.event_type, row.data);
        Event {
            id: row.id,
            event_type: row.event_type,
            ts: row.ts,
            session_id: row.session_id,
            context: serde_json::from_value(row.context).unwrap_or_default(),
            data,
            metadata: row.metadata,
            tags: row.tags,
            sequence: Some(row.sequence),
        }
    }
}
