// Event service for business logic
//
// Events are SSE notifications following the standard event protocol.
// This service is the central entry point for event ingestion from both
// HTTP API and gRPC service.
//
// Decision: Ephemeral delta events skip PostgreSQL only when NATS-backed
// EventDelivery is active (NATS_URL set). Without NATS, all events persist
// to PG as before — zero behavioral change.
// Durable events always go to PG AND EventDelivery.
// SSE streams subscribe to EventDelivery instead of polling PG.
//
// IMPORTANT: Event IDs are ALWAYS generated by the database (uuidv7())
// for durable events. Ephemeral events get a locally-generated ID only
// when NATS is active; otherwise they go through PG like any other event.
//
// Event Listeners:
// After persisting events, the service notifies registered listeners for
// observability integrations (OTel spans, metrics, etc.). Listeners are
// called synchronously but should be non-blocking.

use crate::event_delivery::EventDelivery;
use crate::storage::{
    EventRow, StorageBackend,
    models::{CreateEventRow, EventsSummary as EventsSummaryRow, ListEventsParams},
};
use anyhow::{Result, bail};
use everruns_core::events::{INPUT_MESSAGE, OUTPUT_MESSAGE_COMPLETED};
use everruns_core::{Event, EventListener, EventRequest};
use everruns_platform::{FeatureFlags, SessionParticipantKind};
use everruns_provider::typed_id::{AgentId, AgentVersionId, EventId, PrincipalId, SessionId};
use moka::future::Cache;
use std::sync::Arc;
use std::time::Duration;
use uuid::Uuid;

/// Bound the per-session agent-version metadata cache so a long-lived server
/// cannot leak memory: previously one entry was inserted per session and never
/// evicted. 10k entries covers active fleets; the 30-minute TTL drops stale
/// sessions and keeps memory predictable. Mirrors the PAT auth cache
/// (`auth::builtin`) and reuses the same moka version.
const AGENT_VERSION_METADATA_CACHE_MAX_CAPACITY: u64 = 10_000;
const AGENT_VERSION_METADATA_CACHE_TTL: Duration = Duration::from_secs(30 * 60); // 30 minutes

#[derive(Clone)]
struct AgentVersionEventMetadata {
    agent_id: Option<AgentId>,
    agent_version_id: Option<AgentVersionId>,
    agent_config_hash: Option<String>,
}

#[derive(Clone)]
pub struct EventService {
    db: Arc<StorageBackend>,
    /// Real-time event delivery (NATS / in-memory) for SSE push
    event_delivery: EventDelivery,
    /// Registered event listeners for observability
    listeners: Arc<Vec<Arc<dyn EventListener>>>,
    /// Bounded cache: session_id -> agent-version metadata. moka is internally
    /// `Arc`-backed and `Clone`, so no outer `Arc<RwLock>` is needed.
    agent_version_metadata_cache: Cache<SessionId, AgentVersionEventMetadata>,
}

fn build_agent_version_metadata_cache() -> Cache<SessionId, AgentVersionEventMetadata> {
    Cache::builder()
        .max_capacity(AGENT_VERSION_METADATA_CACHE_MAX_CAPACITY)
        .time_to_live(AGENT_VERSION_METADATA_CACHE_TTL)
        .build()
}

impl EventService {
    pub fn new(db: Arc<StorageBackend>, event_delivery: EventDelivery) -> Self {
        Self {
            db,
            event_delivery,
            listeners: Arc::new(Vec::new()),
            agent_version_metadata_cache: build_agent_version_metadata_cache(),
        }
    }

    /// Create an EventService with registered listeners
    pub fn with_listeners(
        db: Arc<StorageBackend>,
        event_delivery: EventDelivery,
        listeners: Vec<Arc<dyn EventListener>>,
    ) -> Self {
        Self {
            db,
            event_delivery,
            listeners: Arc::new(listeners),
            agent_version_metadata_cache: build_agent_version_metadata_cache(),
        }
    }

    /// Get reference to the event delivery backend (for SSE subscriptions).
    pub fn event_delivery(&self) -> &EventDelivery {
        &self.event_delivery
    }

    /// Notify all registered listeners about an event.
    ///
    /// Each listener is called in isolation - if a listener panics or fails,
    /// other listeners are still notified. This ensures misbehaving listeners
    /// cannot disrupt event processing.
    async fn notify_listeners(&self, event: &Event) {
        for listener in self.listeners.iter() {
            // Check if listener wants this event type
            let should_notify = listener
                .event_types()
                .map(|types| types.contains(&event.event_type.as_str()))
                .unwrap_or(true); // None means all events

            if should_notify {
                let listener_name = listener.name();
                let listener = listener.clone();
                let event = event.clone();

                // Spawn listener in isolated task to catch panics
                let handle = tokio::spawn(async move {
                    listener.on_event(&event).await;
                });

                // Wait for completion, log but don't propagate panics
                if let Err(e) = handle.await {
                    tracing::error!(
                        listener = listener_name,
                        error = %e,
                        "EventListener panicked or was cancelled"
                    );
                }
            }
        }
    }

    /// Validate that event_type matches the data type.
    /// Unsupported events are rejected - they should not be emitted via this service.
    fn validate_event_type_consistency(request: &EventRequest) -> Result<()> {
        // Reject unsupported events - they should never be created, only encountered during read
        if request.data.is_unsupported() {
            bail!("cannot emit unsupported event type");
        }

        let data_event_type = request.data.event_type();

        // Validate consistency between declared type and data type
        if request.event_type != data_event_type {
            bail!(
                "event type mismatch: declared '{}' but data indicates '{}'",
                request.event_type,
                data_event_type
            );
        }

        Ok(())
    }

    /// Emit a typed event request.
    ///
    /// Routing:
    /// - **Ephemeral** delta events when NATS is active:
    ///   published to EventDelivery only. No PG write, no sequence allocation.
    /// - **All events** when NATS is not active (InMemory mode): stored in PG
    ///   as before. No behavioral change without explicit NATS opt-in.
    /// - **Durable** events: always stored in PG + published to EventDelivery.
    ///
    /// All registered listeners are notified regardless of durability.
    ///
    /// # Errors
    /// Returns an error if event_type doesn't match the data type.
    pub async fn emit(&self, mut request: EventRequest) -> Result<Event> {
        self.attach_agent_version_metadata(&mut request).await;
        self.attach_session_participant_metadata(&mut request).await;
        Self::validate_event_type_consistency(&request)?;

        // Only skip PG for delta events when the delivery backend supports it
        // (NATS provides durable pub/sub with replay). InMemory mode persists
        // everything to PG — zero behavioral change without NATS_URL.
        if request.is_ephemeral() && self.event_delivery.supports_ephemeral_skip() {
            return self.emit_ephemeral(request).await;
        }

        self.emit_durable(request).await
    }

    async fn attach_agent_version_metadata(&self, request: &mut EventRequest) {
        if !FeatureFlags::current().agent_versions {
            return;
        };

        let session_metadata = if let Some(cached) = self
            .agent_version_metadata_cache
            .get(&request.session_id)
            .await
        {
            cached
        } else {
            let Ok(Some(session)) = self.db.get_session_unscoped(request.session_id).await else {
                return;
            };
            let metadata = AgentVersionEventMetadata {
                agent_id: session.agent_id,
                agent_version_id: session.agent_version_id,
                agent_config_hash: session.agent_config_hash,
            };
            self.agent_version_metadata_cache
                .insert(request.session_id, metadata.clone())
                .await;
            metadata
        };
        if session_metadata.agent_id.is_none() && session_metadata.agent_version_id.is_none() {
            return;
        }

        let mut metadata = request
            .metadata
            .take()
            .and_then(|v| v.as_object().cloned())
            .unwrap_or_default();
        if let Some(agent_id) = session_metadata.agent_id {
            metadata
                .entry("agent_id".to_string())
                .or_insert_with(|| serde_json::Value::String(agent_id.to_string()));
        }
        if let Some(version_id) = session_metadata.agent_version_id {
            metadata
                .entry("agent_version_id".to_string())
                .or_insert_with(|| serde_json::Value::String(version_id.to_string()));
        }
        if let Some(hash) = session_metadata.agent_config_hash {
            metadata
                .entry("agent_config_hash".to_string())
                .or_insert_with(|| serde_json::Value::String(hash));
        }
        request.metadata = Some(serde_json::Value::Object(metadata));
    }

    async fn attach_session_participant_metadata(&self, request: &mut EventRequest) {
        if request.event_type != INPUT_MESSAGE && request.event_type != OUTPUT_MESSAGE_COMPLETED {
            return;
        }

        let mut metadata = match request.metadata.take() {
            Some(serde_json::Value::Object(map)) => map,
            Some(other) => {
                request.metadata = Some(other);
                return;
            }
            None => return,
        };

        if metadata.contains_key("participant_id") {
            request.metadata = Some(serde_json::Value::Object(metadata));
            return;
        }

        let participant = match request.event_type.as_str() {
            INPUT_MESSAGE => {
                let principal_id = metadata
                    .get("initiator_principal_id")
                    .and_then(|value| value.as_str())
                    .and_then(|value| value.parse::<PrincipalId>().ok());
                match principal_id {
                    Some(principal_id) => {
                        self.find_active_participant(request.session_id, |row| {
                            row.kind == SessionParticipantKind::User.to_string()
                                && row.principal_id == principal_id
                        })
                        .await
                    }
                    None => None,
                }
            }
            OUTPUT_MESSAGE_COMPLETED => {
                let agent_id = metadata
                    .get("agent_id")
                    .and_then(|value| value.as_str())
                    .and_then(|value| value.parse::<AgentId>().ok());
                match agent_id {
                    Some(agent_id) => {
                        self.find_active_participant(request.session_id, |row| {
                            row.kind == SessionParticipantKind::Agent.to_string()
                                && row.agent_id == Some(agent_id)
                        })
                        .await
                    }
                    None => None,
                }
            }
            _ => None,
        };

        if let Some(participant_id) = participant {
            metadata.insert(
                "participant_id".to_string(),
                serde_json::Value::String(participant_id.to_string()),
            );
        }

        request.metadata = Some(serde_json::Value::Object(metadata));
    }

    async fn find_active_participant<F>(
        &self,
        session_id: SessionId,
        matches_participant: F,
    ) -> Option<everruns_provider::typed_id::SessionParticipantId>
    where
        F: Fn(&crate::storage::models::SessionParticipantRow) -> bool,
    {
        let session = self
            .db
            .get_session_unscoped(session_id)
            .await
            .ok()
            .flatten()?;
        self.db
            .list_session_participants(session.org_id, session_id)
            .await
            .ok()?
            .into_iter()
            .find(|row| row.left_at.is_none() && matches_participant(row))
            .map(|row| row.id)
    }

    /// Emit an ephemeral event (skip PG, deliver via EventDelivery only).
    async fn emit_ephemeral(&self, request: EventRequest) -> Result<Event> {
        tracing::debug!(
            session_id = %request.session_id,
            event_type = %request.event_type,
            "EventService: ephemeral event (skipping PG)"
        );

        // Create a synthetic Event with locally-generated ID, no PG sequence
        let event = Event {
            id: EventId::new(),
            event_type: request.event_type,
            ts: request.ts,
            session_id: request.session_id,
            context: request.context,
            data: request.data,
            metadata: request.metadata,
            tags: request.tags,
            sequence: None,
        };

        // Publish to EventDelivery for SSE subscribers
        if let Err(e) = self.event_delivery.publish(&event).await {
            tracing::warn!(
                error = %e,
                event_type = %event.event_type,
                "Failed to publish ephemeral event to delivery backend"
            );
        }

        // Notify listeners (OTel, metrics) even for ephemeral events
        self.notify_listeners(&event).await;

        Ok(event)
    }

    /// Emit a durable event (store in PG + publish to EventDelivery).
    async fn emit_durable(&self, request: EventRequest) -> Result<Event> {
        let create_row = CreateEventRow {
            session_id: request.session_id,
            event_type: request.event_type,
            ts: request.ts,
            context: serde_json::to_value(&request.context)?,
            data: serde_json::to_value(&request.data)?,
            metadata: request.metadata,
            tags: request.tags,
        };

        let row = self.db.create_event(create_row).await?;
        let event = Self::row_to_event(row);

        // Publish to EventDelivery for SSE subscribers
        if let Err(e) = self.event_delivery.publish(&event).await {
            tracing::warn!(
                error = %e,
                event_type = %event.event_type,
                "Failed to publish durable event to delivery backend"
            );
        }

        // Notify listeners after persisting
        self.notify_listeners(&event).await;

        Ok(event)
    }

    /// Emit a batch of typed event requests.
    /// Ephemeral delta events skip PG only when NATS is active; otherwise all go to PG.
    /// Returns the count of successfully processed events.
    ///
    /// # Errors
    /// Returns an error if any event_type doesn't match the data type.
    pub async fn emit_batch(&self, requests: Vec<EventRequest>) -> Result<i32> {
        // Validate all requests first to fail fast
        for request in &requests {
            Self::validate_event_type_consistency(request)?;
        }

        let skip_ephemeral = self.event_delivery.supports_ephemeral_skip();
        let mut count = 0i32;

        for request in requests {
            if request.is_ephemeral() && skip_ephemeral {
                self.emit_ephemeral(request).await?;
            } else {
                self.emit_durable(request).await?;
            }
            count += 1;
        }

        Ok(count)
    }

    /// Create an event from raw row data
    pub async fn create(&self, input: CreateEventRow) -> Result<Event> {
        let row = self.db.create_event(input).await?;
        let event = Self::row_to_event(row);

        // Notify listeners after persisting
        self.notify_listeners(&event).await;

        Ok(event)
    }

    /// List events for a session, filtering out unsupported events.
    /// Unsupported events are internal and never exposed via API.
    /// `filter_types`: positive filter — when non-empty, only return matching types.
    /// `exclude_types`: negative filter — remove matching types from the result.
    /// When both are provided, `filter_types` narrows first, then `exclude_types` removes.
    /// `before_sequence`: cursor for backward pagination (events before this sequence).
    /// `limit`: max number of events to return (backward pagination, last N events).
    #[allow(clippy::too_many_arguments)]
    pub async fn list(
        &self,
        session_id: Uuid,
        since_sequence: Option<i32>,
        since_id: Option<Uuid>,
        filter_types: &[String],
        exclude_types: &[String],
        before_sequence: Option<i32>,
        limit: Option<i32>,
    ) -> Result<Vec<Event>> {
        let rows = self
            .db
            .list_events(
                SessionId::from_uuid(session_id),
                since_sequence,
                since_id.map(EventId::from_uuid),
                filter_types,
                exclude_types,
                before_sequence,
                limit,
            )
            .await?;
        Ok(rows
            .into_iter()
            .map(Self::row_to_event)
            .filter(|e| !e.is_unsupported())
            .collect())
    }

    /// Advanced event listing for debugging.
    ///
    /// Filters out unsupported events. Order follows `params.order_desc`
    /// (DESC = newest first; ASC = oldest first; the `around_id` window is
    /// always returned ASC regardless of the flag).
    pub async fn list_advanced(&self, params: &ListEventsParams) -> Result<Vec<Event>> {
        let rows = self.db.list_events_advanced(params).await?;
        Ok(rows
            .into_iter()
            .map(Self::row_to_event)
            .filter(|e| !e.is_unsupported())
            .collect())
    }

    /// Per-type event count summary (for debug snapshot tooling).
    pub async fn summary(&self, session_id: Uuid) -> Result<EventsSummaryRow> {
        self.db
            .events_summary(SessionId::from_uuid(session_id))
            .await
    }

    /// Count events for a session, excluding specified types (for X-Total-Count header).
    pub async fn count_events(&self, session_id: Uuid, exclude_types: &[String]) -> Result<i64> {
        self.db
            .count_events(SessionId::from_uuid(session_id), exclude_types)
            .await
    }

    /// Find the nearest turn.started sequence at or before the given sequence.
    /// Used for turn boundary snapping in pagination.
    pub async fn find_turn_boundary(
        &self,
        session_id: Uuid,
        before_sequence: i32,
    ) -> Result<Option<i32>> {
        self.db
            .find_turn_boundary(SessionId::from_uuid(session_id), before_sequence)
            .await
    }

    /// List events that represent messages (user, agent, tool results)
    /// Used by gRPC service to load conversation history for workers.
    /// Filters out unsupported events.
    pub async fn list_message_events(&self, session_id: Uuid) -> Result<Vec<Event>> {
        self.list_message_events_limited(session_id, None).await
    }

    /// List message events with an optional limit on count.
    /// Returns most recent N messages in sequence order when limit is provided.
    pub async fn list_message_events_limited(
        &self,
        session_id: Uuid,
        limit: Option<i32>,
    ) -> Result<Vec<Event>> {
        let rows = self
            .db
            .list_message_events_limited(SessionId::from_uuid(session_id), limit)
            .await?;
        Ok(rows
            .into_iter()
            .map(Self::row_to_event)
            .filter(|e| !e.is_unsupported())
            .collect())
    }

    pub(crate) fn row_to_event(row: EventRow) -> Event {
        // Direct mapping from row columns to Event fields
        // Use the core library's deserialize_event_data for proper type handling
        let data = everruns_core::events::deserialize_event_data(&row.event_type, row.data);
        Event {
            id: row.id,
            event_type: row.event_type,
            ts: row.ts,
            session_id: row.session_id,
            context: serde_json::from_value(row.context).unwrap_or_default(),
            data,
            metadata: row.metadata,
            tags: row.tags,
            sequence: Some(row.sequence),
        }
    }
}

/// Core EventEmitter bridge so storage-layer registries (session tasks) can
/// emit through the same persistence + delivery path as the worker.
#[async_trait::async_trait]
impl everruns_core::event_emitter::EventEmitter for EventService {
    async fn emit(
        &self,
        request: EventRequest,
    ) -> everruns_provider::error::Result<everruns_core::Event> {
        EventService::emit(self, request)
            .await
            .map_err(|e| everruns_provider::error::AgentLoopError::event(e.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::event_delivery::EventDelivery;
    use crate::storage::StorageBackend;
    use crate::storage::models::{CreateSessionParticipantRow, CreateSessionRow};
    use everruns_core::events::{EventContext, InputMessageData, OutputMessageCompletedData};
    use everruns_core::{DEFAULT_ORG_ID, Message};
    use everruns_platform::SessionParticipantRole;
    use everruns_provider::typed_id::{AgentId, HarnessId, PrincipalId};
    use std::sync::Arc;

    fn sample_metadata() -> AgentVersionEventMetadata {
        AgentVersionEventMetadata {
            agent_id: None,
            agent_version_id: None,
            agent_config_hash: None,
        }
    }

    /// Inserting far more than `max_capacity` distinct sessions must not grow
    /// the cache unboundedly — this is the regression guard for EVE-638.
    #[tokio::test]
    async fn agent_version_metadata_cache_is_bounded() {
        // Small capacity keeps the test fast while still exercising eviction.
        let cache: Cache<SessionId, AgentVersionEventMetadata> =
            Cache::builder().max_capacity(100).build();

        for _ in 0..10_000 {
            cache.insert(SessionId::new(), sample_metadata()).await;
        }

        // Force moka's async eviction tasks to run so entry_count is accurate.
        cache.run_pending_tasks().await;

        assert!(
            cache.entry_count() <= 100,
            "cache grew beyond max_capacity: {}",
            cache.entry_count()
        );
    }

    /// The real EventService cache is constructed with the bounded settings.
    #[tokio::test]
    async fn event_service_cache_round_trips() {
        let cache = build_agent_version_metadata_cache();
        let id = SessionId::new();
        cache.insert(id, sample_metadata()).await;
        assert!(cache.get(&id).await.is_some());
        assert!(cache.get(&SessionId::new()).await.is_none());
    }

    fn test_session_input(agent_id: AgentId) -> CreateSessionRow {
        CreateSessionRow {
            source: everruns_platform::SessionSource::Api,
            workspace_id: None,
            org_id: DEFAULT_ORG_ID,
            app_id: None,
            harness_id: Some(HarnessId::from_uuid(Uuid::nil())),
            agent_id: Some(agent_id),
            agent_version_id: None,
            agent_config_hash: None,
            agent_identity_id: None,
            owner_principal_id: PrincipalId::from_seed(1),
            resolved_owner_user_id: None,
            title: None,
            locale: None,
            tags: vec![],
            model_id: None,
            capabilities: serde_json::json!([]),
            tools: serde_json::json!([]),
            mcp_servers: serde_json::json!({}),
            system_prompt: None,
            initial_files: serde_json::Value::Array(vec![]),
            hints: None,
            network_access: None,
            max_iterations: None,
            parallel_tool_calls: None,
            blueprint_id: None,
            blueprint_config: None,
            parent_session_id: None,
            budget_root_session_id: None,
        }
    }

    #[tokio::test]
    async fn message_events_attach_active_participant_metadata() {
        let db = Arc::new(StorageBackend::in_memory());
        let event_service = EventService::new(db.clone(), EventDelivery::in_memory());
        let host_agent_id = AgentId::new();
        let guest_agent_id = AgentId::new();
        let session = db
            .create_session(test_session_input(host_agent_id))
            .await
            .unwrap();
        let guest = db
            .create_session_participant(CreateSessionParticipantRow {
                org_id: DEFAULT_ORG_ID,
                session_id: session.id,
                kind: SessionParticipantKind::Agent,
                agent_id: Some(guest_agent_id),
                agent_version_id: None,
                principal_id: PrincipalId::from_seed(2),
                display_name: None,
                role: SessionParticipantRole::Member,
                joined_at: None,
            })
            .await
            .unwrap();
        let owner_user = db
            .list_session_participants(DEFAULT_ORG_ID, session.id)
            .await
            .unwrap()
            .into_iter()
            .find(|row| row.kind == "user" && row.principal_id == PrincipalId::from_seed(1))
            .unwrap();

        let input = event_service
            .emit(
                EventRequest::new(
                    session.id,
                    EventContext::empty(),
                    InputMessageData::new(Message::user("hello")),
                )
                .with_metadata(serde_json::json!({
                    "initiator_principal_id": PrincipalId::from_seed(1).to_string()
                })),
            )
            .await
            .unwrap();
        assert_eq!(
            input
                .metadata
                .as_ref()
                .and_then(|metadata| metadata.get("participant_id"))
                .and_then(|value| value.as_str()),
            Some(owner_user.id.to_string().as_str())
        );

        let output = event_service
            .emit(
                EventRequest::new(
                    session.id,
                    EventContext::empty(),
                    OutputMessageCompletedData::new(Message::assistant("hi")),
                )
                .with_metadata(serde_json::json!({
                    "agent_id": guest_agent_id.to_string()
                })),
            )
            .await
            .unwrap();
        assert_eq!(
            output
                .metadata
                .as_ref()
                .and_then(|metadata| metadata.get("participant_id"))
                .and_then(|value| value.as_str()),
            Some(guest.id.to_string().as_str())
        );
    }
}
