-- Add status column to messages table
-- Decision: Messages now have status to track processing state
-- Status values: 'pending' (awaiting workflow processing), 'processed' (workflow has handled it)
-- User messages start as 'pending', workflow marks them 'processed' after emitting events
-- Non-user messages (assistant, tool_call, tool_result) are created as 'processed' since they're
-- generated by the workflow itself.

-- Add status column with default 'processed' for backwards compatibility
-- (existing messages were already processed by the old system)
ALTER TABLE messages
ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'processed'
CHECK (status IN ('pending', 'processed'));

-- Index for efficient querying of pending messages
CREATE INDEX idx_messages_session_status ON messages(session_id, status);
