//! `build.rs` helper for [`serve`](https://docs.rs/everruns-serve) (experimental),
//! part of the [Everruns](https://everruns.com) ecosystem.
//!
//! Rust cannot scan the filesystem at runtime the way eve does, so the file
//! layout is captured at build time instead: every file under `agent/` (the
//! always-on `instructions.md`, `skills/<name>/SKILL.md`, …) and the app's
//! `serve.toml` are embedded into the binary. The binary is then the complete
//! behavior; `cargo run -- dev` still re-reads the same files from disk so
//! Markdown edits hot-reload without a rebuild.
//!
//! ```no_run
//! // Inside `fn main` of the app's build.rs:
//! serve_build::embed();
//! ```
//!
//! and once in `main.rs`: `serve::assets!();`

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// Name of the generated file in `OUT_DIR`, included by `serve::assets!()`.
pub const GENERATED: &str = "serve_assets.rs";

/// Embed `agent/**` and `serve.toml` from the crate being built.
///
/// Emits `cargo:rerun-if-changed` for both, so adding a skill re-runs the
/// build script. Panics (failing the build with the message) when the crate
/// layout cannot be read, which is the right outcome inside a build script.
pub fn embed() {
    let manifest_dir = std::env::var_os("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            fail("CARGO_MANIFEST_DIR is not set; call serve_build::embed() from build.rs")
        });
    let out_dir = std::env::var_os("OUT_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| fail("OUT_DIR is not set; call serve_build::embed() from build.rs"));

    let source = match generate(&manifest_dir) {
        Ok(source) => source,
        Err(err) => fail(&format!("serve-build: {err}")),
    };
    if let Err(err) = std::fs::write(out_dir.join(GENERATED), source) {
        fail(&format!("serve-build: writing {GENERATED}: {err}"));
    }
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir.join("agent").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir.join("serve.toml").display()
    );
}

fn fail(message: &str) -> ! {
    // A build script reports failure by exiting non-zero; the message is shown.
    eprintln!("{message}");
    std::process::exit(1)
}

/// Produce the Rust source registering every embedded asset.
///
/// Public for tests and for hosts that want to inspect what a build embeds.
pub fn generate(manifest_dir: &Path) -> std::io::Result<String> {
    let mut out = String::from("// @generated by serve-build. Do not edit.\n");
    let agent_dir = manifest_dir.join("agent");
    let mut files = Vec::new();
    if agent_dir.is_dir() {
        collect(&agent_dir, &mut files)?;
    }
    files.sort();
    for file in files {
        let relative = file
            .strip_prefix(&agent_dir)
            .map_err(std::io::Error::other)?
            .to_string_lossy()
            .replace('\\', "/");
        let absolute = file.to_string_lossy().to_string();
        let _ = writeln!(
            out,
            "::serve::__private::inventory::submit! {{ ::serve::__private::AssetRegistration {{ path: {relative:?}, contents: ::core::include_str!({absolute:?}), disk: {absolute:?} }} }}"
        );
    }
    let config = manifest_dir.join("serve.toml");
    if config.is_file() {
        let absolute = config.to_string_lossy().to_string();
        let _ = writeln!(
            out,
            "::serve::__private::inventory::submit! {{ ::serve::__private::AssetRegistration {{ path: \"@serve.toml\", contents: ::core::include_str!({absolute:?}), disk: {absolute:?} }} }}"
        );
    }
    Ok(out)
}

fn collect(dir: &Path, files: &mut Vec<PathBuf>) -> std::io::Result<()> {
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        let hidden = path
            .file_name()
            .is_some_and(|name| name.to_string_lossy().starts_with('.'));
        if hidden {
            continue;
        }
        if path.is_dir() {
            collect(&path, files)?;
        } else if is_text_asset(&path) {
            files.push(path);
        }
    }
    Ok(())
}

/// Only text assets are embedded; `include_str!` would reject anything else.
fn is_text_asset(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|ext| ext.to_str()),
        Some("md" | "txt" | "json" | "yaml" | "yml" | "toml" | "sql")
    )
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::generate;

    #[test]
    fn embeds_agent_markdown_and_config_but_skips_hidden_and_binary_files() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("agent/skills/sql-style")).unwrap();
        std::fs::write(root.join("agent/instructions.md"), "hi").unwrap();
        std::fs::write(root.join("agent/skills/sql-style/SKILL.md"), "skill").unwrap();
        std::fs::write(root.join("agent/.draft.md"), "hidden").unwrap();
        std::fs::write(root.join("agent/logo.png"), [0u8, 1, 2]).unwrap();
        std::fs::write(root.join("serve.toml"), "name = \"x\"").unwrap();

        let source = generate(root).unwrap();
        assert!(source.contains("path: \"instructions.md\""), "{source}");
        assert!(
            source.contains("path: \"skills/sql-style/SKILL.md\""),
            "{source}"
        );
        assert!(source.contains("path: \"@serve.toml\""), "{source}");
        assert!(!source.contains(".draft.md"), "{source}");
        assert!(!source.contains("logo.png"), "{source}");
    }

    #[test]
    fn a_crate_without_agent_dir_embeds_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let source = generate(dir.path()).unwrap();
        assert_eq!(source.lines().count(), 1, "{source}");
    }
}
