#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]
#![doc = include_str!("../README.md")]

#[cfg(feature = "bashkit")]
pub mod bashkit;
#[cfg(feature = "brave-search")]
pub mod brave_search;
#[cfg(feature = "browserless")]
pub mod browserless;
#[cfg(feature = "cursor")]
pub mod cursor;
#[cfg(feature = "daytona")]
pub mod daytona;
#[cfg(feature = "docker")]
pub mod docker;
#[cfg(feature = "duckduckgo")]
pub mod duckduckgo;
#[cfg(feature = "e2b")]
pub mod e2b;
#[cfg(feature = "filesystem")]
pub mod filesystem;
#[cfg(feature = "github")]
pub mod github;
#[cfg(feature = "lua")]
pub mod lua;
#[cfg(feature = "modal")]
pub mod modal;
#[cfg(feature = "openai-decisions")]
pub mod openai_decisions;
#[cfg(feature = "openai-image")]
pub mod openai_image;
#[cfg(feature = "openrouter")]
pub mod openrouter;
#[cfg(feature = "parallel")]
pub mod parallel;
#[cfg(feature = "typesafe")]
pub mod typesafe;
#[cfg(feature = "web-fetch")]
pub mod web_fetch;
#[cfg(feature = "webhook-channel")]
pub mod webhook_channel;
