// Event service for business logic
//
// Events are SSE notifications following the standard event protocol.
// Events are stored in the events table and streamed to clients via SSE.
// This service is the central entry point for event ingestion from both
// HTTP API and gRPC service.
//
// IMPORTANT: Event IDs are ALWAYS generated by the database (uuidv7()).
// EventRow columns map directly to Event fields - no JSON wrapping needed.
//
// Event Listeners:
// After persisting events, the service notifies registered listeners for
// observability integrations (OTel spans, metrics, etc.). Listeners are
// called synchronously but should be non-blocking.

use crate::storage::{EventRow, StorageBackend, models::CreateEventRow};
use anyhow::{Result, bail};
use everruns_core::typed_id::{EventId, SessionId};
use everruns_core::{Event, EventData, EventListener, EventRequest, UNKNOWN};
use std::sync::Arc;
use uuid::Uuid;

#[derive(Clone)]
pub struct EventService {
    db: Arc<StorageBackend>,
    /// Registered event listeners for observability
    listeners: Arc<Vec<Arc<dyn EventListener>>>,
}

impl EventService {
    pub fn new(db: Arc<StorageBackend>) -> Self {
        Self {
            db,
            listeners: Arc::new(Vec::new()),
        }
    }

    /// Create an EventService with registered listeners
    pub fn with_listeners(db: Arc<StorageBackend>, listeners: Vec<Arc<dyn EventListener>>) -> Self {
        Self {
            db,
            listeners: Arc::new(listeners),
        }
    }

    /// Notify all registered listeners about an event.
    ///
    /// Each listener is called in isolation - if a listener panics or fails,
    /// other listeners are still notified. This ensures misbehaving listeners
    /// cannot disrupt event processing.
    async fn notify_listeners(&self, event: &Event) {
        for listener in self.listeners.iter() {
            // Check if listener wants this event type
            let should_notify = listener
                .event_types()
                .map(|types| types.contains(&event.event_type.as_str()))
                .unwrap_or(true); // None means all events

            if should_notify {
                let listener_name = listener.name();
                let listener = listener.clone();
                let event = event.clone();

                // Spawn listener in isolated task to catch panics
                let handle = tokio::spawn(async move {
                    listener.on_event(&event).await;
                });

                // Wait for completion, log but don't propagate panics
                if let Err(e) = handle.await {
                    tracing::error!(
                        listener = listener_name,
                        error = %e,
                        "EventListener panicked or was cancelled"
                    );
                }
            }
        }
    }

    /// Validate that event_type matches the data type.
    /// Raw/unknown events are exempt from this check.
    fn validate_event_type_consistency(request: &EventRequest) -> Result<()> {
        let data_event_type = request.data.event_type();

        // Raw/unknown events are exempt - they're used for legacy/external events
        if data_event_type == UNKNOWN {
            return Ok(());
        }

        // Validate consistency between declared type and data type
        if request.event_type != data_event_type {
            bail!(
                "event type mismatch: declared '{}' but data indicates '{}'",
                request.event_type,
                data_event_type
            );
        }

        Ok(())
    }

    /// Emit a typed event request and store it in the database.
    /// Returns the stored event with its database-assigned id and sequence number.
    ///
    /// This is the primary method for event ingestion, used by both
    /// HTTP API and gRPC service.
    ///
    /// After storing, all registered listeners are notified.
    ///
    /// Note: The event ID is generated by the database, not by Rust.
    ///
    /// # Errors
    /// Returns an error if event_type doesn't match the data type (except for raw events).
    pub async fn emit(&self, request: EventRequest) -> Result<Event> {
        // Validate event type consistency
        Self::validate_event_type_consistency(&request)?;

        // Log streaming/generation events at info level (temporary for debugging)
        if request.event_type == "agent.thinking"
            || request.event_type == "text.delta"
            || request.event_type == "llm.generation"
        {
            tracing::info!(
                session_id = %request.session_id,
                event_type = %request.event_type,
                "EventService: storing event"
            );
        }

        let create_row = CreateEventRow {
            session_id: request.session_id,
            event_type: request.event_type,
            ts: request.ts,
            context: serde_json::to_value(&request.context)?,
            data: serde_json::to_value(&request.data)?,
            metadata: request.metadata,
            tags: request.tags,
        };

        let row = self.db.create_event(create_row).await?;
        let event = Self::row_to_event(row);

        // Notify listeners after persisting
        self.notify_listeners(&event).await;

        Ok(event)
    }

    /// Emit a batch of typed event requests and store them in the database.
    /// Returns the count of successfully stored events.
    ///
    /// This method is optimized for bulk event ingestion from workers.
    /// All registered listeners are notified for each event.
    ///
    /// # Errors
    /// Returns an error if any event_type doesn't match the data type (except for raw events).
    pub async fn emit_batch(&self, requests: Vec<EventRequest>) -> Result<i32> {
        // Validate all requests first to fail fast
        for request in &requests {
            Self::validate_event_type_consistency(request)?;
        }

        let mut count = 0i32;

        for request in requests {
            let create_row = CreateEventRow {
                session_id: request.session_id,
                event_type: request.event_type,
                ts: request.ts,
                context: serde_json::to_value(&request.context)?,
                data: serde_json::to_value(&request.data)?,
                metadata: request.metadata,
                tags: request.tags,
            };

            let row = self.db.create_event(create_row).await?;
            let event = Self::row_to_event(row);

            // Notify listeners after persisting each event
            self.notify_listeners(&event).await;

            count += 1;
        }

        Ok(count)
    }

    /// Create an event from raw row data
    pub async fn create(&self, input: CreateEventRow) -> Result<Event> {
        let row = self.db.create_event(input).await?;
        let event = Self::row_to_event(row);

        // Notify listeners after persisting
        self.notify_listeners(&event).await;

        Ok(event)
    }

    pub async fn list(
        &self,
        session_id: Uuid,
        since_sequence: Option<i32>,
        since_id: Option<Uuid>,
    ) -> Result<Vec<Event>> {
        let rows = self
            .db
            .list_events(
                SessionId::from_uuid(session_id),
                since_sequence,
                since_id.map(EventId::from_uuid),
            )
            .await?;
        Ok(rows.into_iter().map(Self::row_to_event).collect())
    }

    /// List events that represent messages (user, agent, tool results)
    /// Used by gRPC service to load conversation history for workers.
    pub async fn list_message_events(&self, session_id: Uuid) -> Result<Vec<Event>> {
        let rows = self
            .db
            .list_message_events(SessionId::from_uuid(session_id))
            .await?;
        Ok(rows.into_iter().map(Self::row_to_event).collect())
    }

    fn row_to_event(row: EventRow) -> Event {
        // Direct mapping from row columns to Event fields
        let data =
            serde_json::from_value(row.data.clone()).unwrap_or_else(|_| EventData::raw(row.data));
        Event {
            id: row.id,
            event_type: row.event_type,
            ts: row.ts,
            session_id: row.session_id,
            context: serde_json::from_value(row.context).unwrap_or_default(),
            data,
            metadata: row.metadata,
            tags: row.tags,
            sequence: Some(row.sequence),
        }
    }
}
