#!/usr/bin/env bash
# Ratchet guard on errors interpolated into log messages.
#
# Why: a log pipeline groups on the message. A site that renders the error text
# *into* the message produces a new group for every distinct underlying error,
# so one bug fans out into many issues and none of them names the cause.
# EVERRUNS-15 and EVERRUNS-1Q are the same line of code, split only by which
# error it caught that day. The structured form groups correctly:
#
#   error!("Failed to claim due schedules: {}", e);    // fans out
#   error!(error = %e, "Failed to claim due schedules"); // groups
#
# This guard does not convert anything — that is a ~340-site sweep and belongs
# to whoever is already in the file. It stops the bleeding: a file's count may
# not grow, and no un-allowlisted file may introduce one.
#
# The allowlist is the debt list. Every entry records a file's count when it was
# baselined. A file that gains a site fails; a file that reaches zero must be
# removed from the list, so paying the debt down is recorded rather than
# silently re-earned.
#
# Database-touching sites should convert to `everruns_core::log_database_failure`
# so a shared incident still collapses to one group (EVE-1071). Everything else
# converts to a static message with `error = %e`.
#
# Usage:
#   check-log-error-field.sh            # verify (pre-push, CI)
#   check-log-error-field.sh --update   # re-baseline the allowlist deliberately
#
# Used by: scripts/lib/pre-push.sh, the `log-error-field` CI job.
# Exits 0 on success, 1 on violation. Never silently skips.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

ALLOWLIST="scripts/lib/log-error-field-allowlist.txt"

# A `tracing` error!/warn! whose literal message ends in `: {}` — the shape that
# renders a value into the message. Deliberately narrow: it is the shape the
# Sentry fan-out came from, and a narrow pattern that never false-positives is
# worth more than a broad one people learn to work around.
PATTERN='(error|warn)!\("[^"]*: *\{\}"'

list_source_files() {
  # A file deleted in the working tree is still listed by git until the deletion
  # is staged, so skip what is not on disk; an allowlisted one is then reported
  # as a stale entry rather than crashing the guard.
  git ls-files -z 'crates/**/*.rs' \
    | tr '\0' '\n' \
    | while IFS= read -r file; do
        [ -f "$file" ] && printf '%s\n' "$file"
      done \
    | sort
}

site_count() {
  grep -cE "$PATTERN" "$1" || true
}

if [ "${1:-}" = "--update" ]; then
  {
    echo "# Files that interpolate an error into a log message, with the count"
    echo "# each was baselined at. Generated by:"
    echo "#   bash scripts/lib/check-log-error-field.sh --update"
    echo "#"
    echo "# An entry may not grow. A file that reaches zero must be removed from"
    echo "# this list. Do not add an entry by hand to admit a new site — use"
    echo "# error = %e with a static message instead (EVE-1073)."
    while IFS= read -r file; do
      [ -n "$file" ] || continue
      count="$(site_count "$file")"
      if [ "$count" -gt 0 ]; then
        echo "$count $file"
      fi
    done < <(list_source_files)
  } > "$ALLOWLIST"
  entries="$(grep -cv '^#' "$ALLOWLIST" || true)"
  echo "Baselined $entries files into $ALLOWLIST."
  exit 0
fi

if [ ! -f "$ALLOWLIST" ]; then
  echo "Log-error-field allowlist missing: $ALLOWLIST"
  echo "  Generate it with: bash scripts/lib/check-log-error-field.sh --update"
  exit 1
fi

FAILED=0
TOTAL=0

declare -A ALLOWED=()
while read -r count file; do
  case "$count" in
    ''|'#'*) continue ;;
  esac
  if ! [[ "$count" =~ ^[0-9]+$ ]] || [ -z "$file" ]; then
    echo "  - $ALLOWLIST: malformed entry: $count $file"
    FAILED=1
    continue
  fi
  ALLOWED["$file"]="$count"
done < "$ALLOWLIST"

declare -A SEEN=()

while IFS= read -r file; do
  [ -n "$file" ] || continue
  count="$(site_count "$file")"
  allowed="${ALLOWED[$file]:-}"
  TOTAL=$((TOTAL + count))

  if [ -n "$allowed" ]; then
    SEEN["$file"]=1
    if [ "$count" -eq 0 ]; then
      echo "  - $file: no interpolated sites left"
      echo "      remove its entry from $ALLOWLIST to bank the win"
      FAILED=1
    elif [ "$count" -gt "$allowed" ]; then
      echo "  - $file: grew to $count interpolated sites, baselined at $allowed"
      echo "      use a static message with error = %e instead"
      FAILED=1
    elif [ "$count" -lt "$allowed" ]; then
      echo "  note: $file dropped to $count sites (baselined at $allowed);"
      echo "      run 'bash scripts/lib/check-log-error-field.sh --update' to tighten it"
    fi
  elif [ "$count" -gt 0 ]; then
    echo "  - $file: $count log site(s) interpolate an error into the message"
    echo "      use a static message with error = %e; do not add it to $ALLOWLIST"
    FAILED=1
  fi
done < <(list_source_files)

# Entries for files that were deleted or renamed are stale and hide regressions.
for file in "${!ALLOWED[@]}"; do
  if [ -z "${SEEN[$file]:-}" ]; then
    echo "  - $ALLOWLIST: stale entry for missing file: $file"
    FAILED=1
  fi
done

if [ "$FAILED" -ne 0 ]; then
  echo "Log error-field guard failed."
  exit 1
fi

echo "Log error-field guard passed: ${#ALLOWED[@]} allowlisted files, none grew; $TOTAL sites remaining."
