#!/usr/bin/env bash
# Ratchet guard on source file length.
#
# Why: a handful of files have grown past the point where anyone can hold them
# in their head, and nothing stopped them. This guard does not shrink them —
# splitting is opportunistic work for whoever is already in the file. It stops
# the bleeding: an oversized file may not grow further, and no new file may
# cross the threshold.
#
# The allowlist is the debt list. Every entry records the file's length when it
# was baselined. A file that grows past its recorded length fails; a file that
# drops under the threshold must be removed from the list, so paying the debt
# down is recorded rather than silently re-earned.
#
# Generated files are excluded: their length is the generator's business.
#
# Usage:
#   check-file-size.sh            # verify (pre-push, CI)
#   check-file-size.sh --update   # re-baseline the allowlist deliberately
#
# Used by: scripts/lib/pre-push.sh, the `file-size` CI job.
# Exits 0 on success, 1 on violation. Never silently skips.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

THRESHOLD=1500
ALLOWLIST="scripts/lib/file-size-allowlist.txt"

# Paths excluded from the guard entirely, as extended regex matched against the
# repository-relative path. Generated code only — not an escape hatch.
EXCLUDE_RE='(^apps/ui/src/lib/api/generated/)'

list_source_files() {
  # A file deleted in the working tree is still listed by git until the deletion
  # is staged, so skip what is not on disk; an allowlisted one is then reported
  # as a stale entry rather than crashing the guard.
  git ls-files -z '*.rs' '*.ts' '*.tsx' \
    | tr '\0' '\n' \
    | grep -Ev "$EXCLUDE_RE" \
    | while IFS= read -r file; do
        [ -f "$file" ] && printf '%s\n' "$file"
      done \
    | sort
}

line_count() {
  # Counts lines the way `wc -l` does, so a file missing its trailing newline
  # is not silently one line shorter than it reads.
  wc -l < "$1" | tr -d ' '
}

if [ "${1:-}" = "--update" ]; then
  {
    echo "# Files over $THRESHOLD lines, with the length each was baselined at."
    echo "# Generated by: bash scripts/lib/check-file-size.sh --update"
    echo "#"
    echo "# An entry may not grow. A file that drops under $THRESHOLD lines must be"
    echo "# removed from this list. Do not add an entry by hand to admit a new"
    echo "# oversized file — split the file instead."
    while IFS= read -r file; do
      [ -n "$file" ] || continue
      lines="$(line_count "$file")"
      if [ "$lines" -gt "$THRESHOLD" ]; then
        echo "$lines $file"
      fi
    done < <(list_source_files)
  } > "$ALLOWLIST"
  entries="$(grep -cv '^#' "$ALLOWLIST" || true)"
  echo "Baselined $entries files over $THRESHOLD lines into $ALLOWLIST."
  exit 0
fi

if [ ! -f "$ALLOWLIST" ]; then
  echo "File size allowlist missing: $ALLOWLIST"
  echo "  Generate it with: bash scripts/lib/check-file-size.sh --update"
  exit 1
fi

FAILED=0

# Load the allowlist into two parallel lookups keyed by path.
declare -A ALLOWED_LINES=()
while read -r lines file; do
  case "$lines" in
    ''|'#'*) continue ;;
  esac
  if ! [[ "$lines" =~ ^[0-9]+$ ]] || [ -z "$file" ]; then
    echo "  - $ALLOWLIST: malformed entry: $lines $file"
    FAILED=1
    continue
  fi
  ALLOWED_LINES["$file"]="$lines"
done < "$ALLOWLIST"

declare -A SEEN=()

while IFS= read -r file; do
  [ -n "$file" ] || continue
  lines="$(line_count "$file")"
  allowed="${ALLOWED_LINES[$file]:-}"

  if [ -n "$allowed" ]; then
    SEEN["$file"]=1
    if [ "$lines" -le "$THRESHOLD" ]; then
      echo "  - $file: now $lines lines, under the $THRESHOLD line threshold"
      echo "      remove its entry from $ALLOWLIST to bank the win"
      FAILED=1
    elif [ "$lines" -gt "$allowed" ]; then
      echo "  - $file: grew to $lines lines, baselined at $allowed"
      echo "      an allowlisted file may not grow — move the new code elsewhere"
      FAILED=1
    elif [ "$lines" -lt "$allowed" ]; then
      echo "  note: $file shrank to $lines lines (baselined at $allowed);"
      echo "      run 'bash scripts/lib/check-file-size.sh --update' to tighten it"
    fi
  elif [ "$lines" -gt "$THRESHOLD" ]; then
    echo "  - $file: $lines lines exceeds the $THRESHOLD line threshold"
    echo "      split it; do not add it to $ALLOWLIST"
    FAILED=1
  fi
done < <(list_source_files)

# Entries for files that were deleted or renamed are stale and hide regressions.
for file in "${!ALLOWED_LINES[@]}"; do
  if [ -z "${SEEN[$file]:-}" ]; then
    echo "  - $ALLOWLIST: stale entry for missing file: $file"
    FAILED=1
  fi
done

if [ "$FAILED" -ne 0 ]; then
  echo "File size guard failed."
  exit 1
fi

echo "File size guard passed: ${#ALLOWED_LINES[@]} allowlisted files, none grew; no new file over $THRESHOLD lines."
