#!/usr/bin/env bash
# Ratchet guard on errors interpolated into log messages.
#
# Why: a log pipeline groups on the message. A site that renders the error text
# *into* the message produces a new group for every distinct underlying error,
# so one bug fans out into many issues and none of them names the cause.
# EVERRUNS-15 and EVERRUNS-1Q are the same line of code, split only by which
# error it caught that day. The structured form groups correctly:
#
#   error!("Failed to claim due schedules: {}", e);    // fans out
#   error!(error = %e, "Failed to claim due schedules"); // groups
#
# This guard does not convert anything — that is a ~340-site sweep and belongs
# to whoever is already in the file. It stops the bleeding: a file's count may
# not grow, and no un-allowlisted file may introduce one.
#
# The allowlist is the debt list: the files that still have at least one site. A
# file that reaches zero must be removed from the list, so paying the debt down
# is recorded rather than silently re-earned.
#
# Growth is measured against the merge base with origin/main, not against a
# count committed next to the path. A committed number is a merge hazard
# (EVE-1105, EVE-1107): one pull request converts sites and re-baselines the
# number while another, cut from an older base, changes the same file without
# touching the allowlist. The two commits touch different files, so git reports
# no conflict, and main goes red once both land — on a required check, with no
# single commit at fault. Asking the merge base instead asks the only question a
# guard can answer honestly: did *this change* add a site?
#
# The trade is deliberate. Two branches that both convert sites in one file can,
# merged without a rebase, leave main holding the higher of the two counts. That
# un-banks a win; it never admits a new site, and it never turns main red on work
# that already passed review. On a pull request CI measures the merge of the
# branch and current main, so a branch that would un-bank a win fails there,
# before merge.
#
# Database-touching sites should convert to `everruns_core::log_database_failure`
# so a shared incident still collapses to one group (EVE-1071). Everything else
# converts to a static message with `error = %e`.
#
# Usage:
#   check-log-error-field.sh            # verify (pre-push, CI)
#   check-log-error-field.sh --update   # re-baseline the allowlist deliberately
#
# Set LOG_ERROR_FIELD_BASE_REF to compare against something other than origin/main.
#
# Used by: scripts/lib/pre-push.sh, the `log-error-field` CI job.
# Exits 0 on success, 1 on violation. Never silently skips.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

ALLOWLIST="scripts/lib/log-error-field-allowlist.txt"

# A `tracing` error!/warn! whose literal message ends in `: {}` — the shape that
# renders a value into the message. Deliberately narrow: it is the shape the
# Sentry fan-out came from, and a narrow pattern that never false-positives is
# worth more than a broad one people learn to work around.
PATTERN='(error|warn)!\("[^"]*: *\{\}"'

list_source_files() {
  # A file deleted in the working tree is still listed by git until the deletion
  # is staged, so skip what is not on disk; an allowlisted one is then reported
  # as a stale entry rather than crashing the guard.
  git ls-files -z 'crates/**/*.rs' \
    | tr '\0' '\n' \
    | while IFS= read -r file; do
        [ -f "$file" ] && printf '%s\n' "$file"
      done \
    | sort
}

site_count() {
  grep -cE "$PATTERN" "$1" || true
}

if [ "${1:-}" = "--update" ]; then
  {
    echo "# Files that interpolate an error into a log message: the debt list."
    echo "# Generated by:"
    echo "#   bash scripts/lib/check-log-error-field.sh --update"
    echo "#"
    echo "# Entries carry no count on purpose. Growth is measured against the merge"
    echo "# base with origin/main, because a committed number can be moved by one"
    echo "# pull request while another changes the file, with nothing for git to"
    echo "# report as a conflict (EVE-1107)."
    echo "#"
    echo "# A file that reaches zero must be removed from this list. Do not add an"
    echo "# entry by hand to admit a new site — use error = %e with a static"
    echo "# message instead (EVE-1073)."
    while IFS= read -r file; do
      [ -n "$file" ] || continue
      if [ "$(site_count "$file")" -gt 0 ]; then
        printf '%s\n' "$file"
      fi
    done < <(list_source_files)
  } > "$ALLOWLIST"
  entries="$(grep -cv '^#' "$ALLOWLIST" || true)"
  echo "Baselined $entries files into $ALLOWLIST."
  exit 0
fi

if [ ! -f "$ALLOWLIST" ]; then
  echo "Log-error-field allowlist missing: $ALLOWLIST"
  echo "  Generate it with: bash scripts/lib/check-log-error-field.sh --update"
  exit 1
fi

BASE_REF="${LOG_ERROR_FIELD_BASE_REF:-origin/main}"

if ! git rev-parse --verify -q "$BASE_REF" >/dev/null; then
  if git remote get-url origin >/dev/null 2>&1; then
    git fetch --quiet origin main:refs/remotes/origin/main || true
  fi
fi

if ! git rev-parse --verify -q "$BASE_REF" >/dev/null; then
  echo "Could not resolve the log-error-field base ref: $BASE_REF" >&2
  echo "Fetch origin/main or set LOG_ERROR_FIELD_BASE_REF." >&2
  exit 1
fi

if ! MERGE_BASE="$(git merge-base HEAD "$BASE_REF")"; then
  echo "No common history between HEAD and $BASE_REF; cannot measure growth." >&2
  exit 1
fi
readonly MERGE_BASE

FAILED=0
TOTAL=0

declare -A ALLOWED=()
while IFS= read -r file; do
  case "$file" in
    ''|'#'*) continue ;;
  esac
  case "$file" in
    *[[:space:]]*)
      # The old format carried "<count> <path>". An entry still in that shape
      # would silently never match a real path, so say so instead.
      echo "  - $ALLOWLIST: malformed entry (paths only, no count): $file"
      FAILED=1
      continue
      ;;
  esac
  ALLOWED["$file"]=1
done < "$ALLOWLIST"

# A rename is not a new site. Measure the new path against where it came from.
declare -A RENAMED_FROM=()
while IFS=$'\t' read -r status old new; do
  case "$status" in
    R*) [ -n "${new:-}" ] && RENAMED_FROM["$new"]="$old" ;;
  esac
done < <(git diff --name-status --find-renames "$MERGE_BASE" HEAD -- 'crates/**/*.rs')

base_site_count() {
  # Empty when the path does not exist at the merge base.
  local path="$1"
  git cat-file -e "$MERGE_BASE:$path" 2>/dev/null || return 0
  git show "$MERGE_BASE:$path" | grep -cE "$PATTERN" || true
}

declare -A SEEN=()

while IFS= read -r file; do
  [ -n "$file" ] || continue
  count="$(site_count "$file")"
  TOTAL=$((TOTAL + count))

  if [ -n "${ALLOWED[$file]:-}" ]; then
    SEEN["$file"]=1
    if [ "$count" -eq 0 ]; then
      echo "  - $file: no interpolated sites left"
      echo "      remove its entry from $ALLOWLIST to bank the win"
      FAILED=1
      continue
    fi

    base_path="${RENAMED_FROM[$file]:-$file}"
    base_count="$(base_site_count "$base_path")"

    if [ -z "$base_count" ]; then
      echo "  - $file: new on this branch and already has $count interpolated site(s)"
      echo "      use a static message with error = %e; an allowlist entry does not admit one"
      FAILED=1
    elif [ "$count" -gt "$base_count" ]; then
      echo "  - $file: grew to $count interpolated sites, from $base_count at the merge base"
      echo "      use a static message with error = %e instead"
      FAILED=1
    fi
  elif [ "$count" -gt 0 ]; then
    echo "  - $file: $count log site(s) interpolate an error into the message"
    echo "      use a static message with error = %e; do not add it to $ALLOWLIST"
    FAILED=1
  fi
done < <(list_source_files)

# Entries for files that were deleted or renamed are stale and hide regressions.
for file in "${!ALLOWED[@]}"; do
  if [ -z "${SEEN[$file]:-}" ]; then
    echo "  - $ALLOWLIST: stale entry for missing file: $file"
    FAILED=1
  fi
done

if [ "$FAILED" -ne 0 ]; then
  echo "Log error-field guard failed."
  exit 1
fi

if [ "$MERGE_BASE" = "$(git rev-parse HEAD)" ]; then
  growth_scope="HEAD is the base ($BASE_REF), so nothing here is a change yet"
else
  growth_scope="measured against $(git rev-parse --short "$MERGE_BASE"), the merge base with $BASE_REF"
fi

echo "Log error-field guard passed: ${#ALLOWED[@]} allowlisted files, none grew; $TOTAL sites remaining ($growth_scope)."
