#!/usr/bin/env bash
# Ratchet guard on source file length.
#
# Why: a handful of files have grown past the point where anyone can hold them
# in their head, and nothing stopped them. This guard does not shrink them —
# splitting is opportunistic work for whoever is already in the file. It stops
# the bleeding: an oversized file may not grow further, and no new file may
# cross the threshold.
#
# The allowlist is the debt list: the files already over the threshold. A file
# that drops under it must be removed from the list, so paying the debt down is
# recorded rather than silently re-earned.
#
# Growth is measured against the merge base with origin/main, not against a
# line count committed next to the path. A committed number is a merge hazard
# (EVE-1105): one PR re-baselines it while another, cut from an older base,
# changes the file's length without touching the allowlist. The two commits
# touch different files, so git reports no conflict, and main goes red once both
# land — blaming a file that is fine and a number that is stale. Asking the
# merge base instead asks the only question a guard can answer honestly: did
# *this change* grow the file?
#
# The trade is deliberate. Two branches that both shrink a file can, merged
# without a rebase, leave main holding the larger of the two. That un-banks a
# win; it never admits growth, and it never turns main red on work that already
# passed review. On a pull request CI measures the merge of the branch and
# current main, so a branch that would un-bank a win fails there, before merge.
#
# Generated files are excluded: their length is the generator's business.
#
# Usage:
#   check-file-size.sh            # verify (pre-push, CI)
#   check-file-size.sh --update   # re-baseline the allowlist deliberately
#
# Set FILE_SIZE_BASE_REF to compare against something other than origin/main.
#
# Used by: scripts/lib/pre-push.sh, the `file-size` CI job.
# Exits 0 on success, 1 on violation. Never silently skips.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

THRESHOLD=1500
ALLOWLIST="scripts/lib/file-size-allowlist.txt"

# Paths excluded from the guard entirely, as extended regex matched against the
# repository-relative path. Generated code only — not an escape hatch.
EXCLUDE_RE='(^apps/ui/src/lib/api/generated/)'

list_source_files() {
  # A file deleted in the working tree is still listed by git until the deletion
  # is staged, so skip what is not on disk; an allowlisted one is then reported
  # as a stale entry rather than crashing the guard.
  git ls-files -z '*.rs' '*.ts' '*.tsx' \
    | tr '\0' '\n' \
    | grep -Ev "$EXCLUDE_RE" \
    | while IFS= read -r file; do
        [ -f "$file" ] && printf '%s\n' "$file"
      done \
    | sort
}

line_count() {
  # Counts lines the way `wc -l` does, so a file missing its trailing newline
  # is not silently one line shorter than it reads.
  wc -l < "$1" | tr -d ' '
}

if [ "${1:-}" = "--update" ]; then
  {
    echo "# Files over $THRESHOLD lines: the debt list."
    echo "# Generated by: bash scripts/lib/check-file-size.sh --update"
    echo "#"
    echo "# Entries carry no line count on purpose. Growth is measured against the"
    echo "# merge base with origin/main, because a committed number can be moved by"
    echo "# one pull request while another changes the file, with nothing for git to"
    echo "# report as a conflict (EVE-1105)."
    echo "#"
    echo "# A file that drops under $THRESHOLD lines must be removed from this list."
    echo "# Do not add an entry by hand to admit a new oversized file — split the"
    echo "# file instead."
    while IFS= read -r file; do
      [ -n "$file" ] || continue
      if [ "$(line_count "$file")" -gt "$THRESHOLD" ]; then
        printf '%s\n' "$file"
      fi
    done < <(list_source_files)
  } > "$ALLOWLIST"
  entries="$(grep -cv '^#' "$ALLOWLIST" || true)"
  echo "Baselined $entries files over $THRESHOLD lines into $ALLOWLIST."
  exit 0
fi

if [ ! -f "$ALLOWLIST" ]; then
  echo "File size allowlist missing: $ALLOWLIST"
  echo "  Generate it with: bash scripts/lib/check-file-size.sh --update"
  exit 1
fi

BASE_REF="${FILE_SIZE_BASE_REF:-origin/main}"

if ! git rev-parse --verify -q "$BASE_REF" >/dev/null; then
  if git remote get-url origin >/dev/null 2>&1; then
    git fetch --quiet origin main:refs/remotes/origin/main || true
  fi
fi

if ! git rev-parse --verify -q "$BASE_REF" >/dev/null; then
  echo "Could not resolve the file size base ref: $BASE_REF" >&2
  echo "Fetch origin/main or set FILE_SIZE_BASE_REF." >&2
  exit 1
fi

if ! MERGE_BASE="$(git merge-base HEAD "$BASE_REF")"; then
  echo "No common history between HEAD and $BASE_REF; cannot measure growth." >&2
  exit 1
fi
readonly MERGE_BASE

FAILED=0

declare -A ALLOWED=()
while IFS= read -r file; do
  case "$file" in
    ''|'#'*) continue ;;
  esac
  case "$file" in
    *[[:space:]]*)
      # The old format carried "<lines> <path>". An entry still in that shape
      # would silently never match a real path, so say so instead.
      echo "  - $ALLOWLIST: malformed entry (paths only, no line count): $file"
      FAILED=1
      continue
      ;;
  esac
  ALLOWED["$file"]=1
done < "$ALLOWLIST"

# A rename is not growth. Measure the new path against the content it came from.
declare -A RENAMED_FROM=()
while IFS=$'\t' read -r status old new; do
  case "$status" in
    R*) [ -n "${new:-}" ] && RENAMED_FROM["$new"]="$old" ;;
  esac
done < <(git diff --name-status --find-renames "$MERGE_BASE" HEAD -- '*.rs' '*.ts' '*.tsx')

base_line_count() {
  # Empty when the path does not exist at the merge base.
  local path="$1"
  git cat-file -e "$MERGE_BASE:$path" 2>/dev/null || return 0
  git show "$MERGE_BASE:$path" | wc -l | tr -d ' '
}

declare -A SEEN=()

while IFS= read -r file; do
  [ -n "$file" ] || continue
  lines="$(line_count "$file")"

  if [ -n "${ALLOWED[$file]:-}" ]; then
    SEEN["$file"]=1

    if [ "$lines" -le "$THRESHOLD" ]; then
      echo "  - $file: now $lines lines, under the $THRESHOLD line threshold"
      echo "      remove its entry from $ALLOWLIST to bank the win"
      FAILED=1
      continue
    fi

    base_path="${RENAMED_FROM[$file]:-$file}"
    base_lines="$(base_line_count "$base_path")"

    if [ -z "$base_lines" ]; then
      echo "  - $file: new on this branch and already $lines lines, over the $THRESHOLD line threshold"
      echo "      split it; an allowlist entry does not admit a new oversized file"
      FAILED=1
    elif [ "$lines" -gt "$base_lines" ]; then
      echo "  - $file: grew to $lines lines, from $base_lines at the merge base"
      echo "      an allowlisted file may not grow — move the new code elsewhere"
      FAILED=1
    fi
  elif [ "$lines" -gt "$THRESHOLD" ]; then
    echo "  - $file: $lines lines exceeds the $THRESHOLD line threshold"
    echo "      split it; do not add it to $ALLOWLIST"
    FAILED=1
  fi
done < <(list_source_files)

# Entries for files that were deleted or renamed are stale and hide regressions.
for file in "${!ALLOWED[@]}"; do
  if [ -z "${SEEN[$file]:-}" ]; then
    echo "  - $ALLOWLIST: stale entry for missing file: $file"
    FAILED=1
  fi
done

if [ "$FAILED" -ne 0 ]; then
  echo "File size guard failed."
  exit 1
fi

if [ "$MERGE_BASE" = "$(git rev-parse HEAD)" ]; then
  growth_scope="HEAD is the base ($BASE_REF), so nothing here is a change yet"
else
  growth_scope="measured against $(git rev-parse --short "$MERGE_BASE"), the merge base with $BASE_REF"
fi

echo "File size guard passed: ${#ALLOWED[@]} allowlisted files, none grew; no new file over $THRESHOLD lines ($growth_scope)."
