// PostgreSQL repository: Events (source of truth for messages)

use super::super::models::*;
use super::super::repository::MESSAGE_SAFETY_LIMIT;
use super::Database;
use anyhow::Result;
use chrono::{DateTime, Utc};
use everruns_core::message_filter::{MessageFilter, MessageQuery};
use everruns_provider::typed_id::{EventId, SessionId};
use tracing::warn;
use uuid::Uuid;

use crate::storage::message_history_timing::{
    FILTERED_MESSAGE_HISTORY_EVENTS, MESSAGE_HISTORY_EVENTS, maybe_warn_slow_message_history,
};

/// Shared filter builder for `list_events_advanced` (and its `around_id` branch).
/// Pushes type/time/context/tag/tool/search predicates onto the running query.
fn push_common_filters(qb: &mut sqlx::QueryBuilder<sqlx::Postgres>, params: &ListEventsParams) {
    if !params.filter_types.is_empty() {
        qb.push(" AND event_type = ANY(");
        qb.push_bind(params.filter_types.clone());
        qb.push(")");
    }
    if !params.exclude_types.is_empty() {
        qb.push(" AND event_type <> ALL(");
        qb.push_bind(params.exclude_types.clone());
        qb.push(")");
    }
    if let Some(from) = params.from_ts {
        qb.push(" AND created_at >= ");
        qb.push_bind(from);
    }
    if let Some(to) = params.to_ts {
        qb.push(" AND created_at <= ");
        qb.push_bind(to);
    }
    if let Some(turn_id) = params.turn_id.as_deref() {
        qb.push(" AND context->>'turn_id' = ");
        qb.push_bind(turn_id.to_string());
    }
    if let Some(exec_id) = params.exec_id.as_deref() {
        qb.push(" AND context->>'exec_id' = ");
        qb.push_bind(exec_id.to_string());
    }
    if let Some(trace_id) = params.trace_id.as_deref() {
        qb.push(" AND context->>'trace_id' = ");
        qb.push_bind(trace_id.to_string());
    }
    if !params.tags.is_empty() {
        qb.push(" AND tags && ");
        qb.push_bind(params.tags.clone());
    }
    if let Some(tool_name) = params.tool_name.as_deref() {
        qb.push(" AND data->>'tool_name' = ");
        qb.push_bind(tool_name.to_string());
    }
    if let Some(q) = params.q.as_deref() {
        qb.push(" AND search_vector @@ plainto_tsquery('english', ");
        qb.push_bind(q.to_string());
        qb.push(")");
    }
}

/// Safety cap for otherwise-unbounded full-history message reads. Applied to
/// both `list_message_events_limited` (no explicit limit) and the
/// `(offset=None, limit=None)` branch of `list_message_events_filtered`, so
/// neither path can materialize an unbounded result set for a huge session.
impl Database {
    // ============================================
    // Events (source of truth for messages)
    // ============================================
    //
    // Messages are stored as events with type "message.*"
    // Use list_message_events() to load conversation messages.

    pub async fn create_event(&self, input: CreateEventRow) -> Result<EventRow> {
        // Atomically allocate next sequence number for this session
        // ID is generated by database using uuidv7() for monotonically increasing UUIDs
        let row = sqlx::query_as::<_, EventRow>(
            r#"
            INSERT INTO events (session_id, sequence, event_type, ts, context, data, metadata, tags)
            VALUES ($1, allocate_event_sequence($1), $2, $3, $4, $5, $6, $7)
            RETURNING id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
            "#,
        )
        .bind(input.session_id)
        .bind(&input.event_type)
        .bind(input.ts)
        .bind(&input.context)
        .bind(&input.data)
        .bind(&input.metadata)
        .bind(&input.tags)
        .fetch_one(&self.pool)
        .await?;

        // Reporting outbox enqueue is best-effort per knowledge/evaluation/reporting.md:
        // "If an outbox write fails after canonical state commits, a periodic
        // reconciler must be able to discover and enqueue missing projection
        // work from canonical tables." Never fail the canonical event write
        // because the reporting projector queue is unavailable. No reconciler
        // job exists yet (tracked separately); until it lands, a failed
        // enqueue means the corresponding fact will remain stale until the
        // canonical row is touched again and the next enqueue succeeds.
        if let Err(e) = sqlx::query(
            r#"
            INSERT INTO reporting_outbox (
                org_id, source_type, source_id, source_version, reason, status, next_attempt_at
            )
            SELECT s.org_id, 'event', $1, $1, 'event_projection', 'pending', NOW()
            FROM sessions s
            WHERE s.id = $2
            ON CONFLICT (org_id, source_type, source_id, source_version, reason)
            DO NOTHING
            "#,
        )
        .bind(row.id.uuid().to_string())
        .bind(row.session_id.uuid())
        .execute(&self.pool)
        .await
        {
            // Look up org_id for log correlation. Failure to resolve is
            // expected when sessions row is gone or pool is unhealthy; we
            // still log the underlying error and don't propagate.
            let org_id: Option<i64> =
                sqlx::query_scalar::<_, i64>("SELECT org_id FROM sessions WHERE id = $1")
                    .bind(row.session_id.uuid())
                    .fetch_optional(&self.pool)
                    .await
                    .ok()
                    .flatten();
            warn!(
                event_id = %row.id.uuid(),
                session_id = %row.session_id.uuid(),
                org_id = ?org_id,
                event_type = %row.event_type,
                error = %e,
                "reporting outbox enqueue failed; event persisted, projection may remain stale until reconciliation lands or the source row is updated again"
            );
        }

        Ok(row)
    }

    /// Check if an input.message event with a given slack_ts already exists in a session.
    /// Used for dedup when Slack sends duplicate events (app_mention + message).
    pub async fn has_event_with_slack_ts(
        &self,
        session_id: SessionId,
        slack_ts: &str,
    ) -> Result<bool> {
        let pattern = serde_json::json!({
            "message": { "metadata": { "slack_ts": slack_ts } }
        });
        let row: (bool,) = sqlx::query_as(
            r#"
            SELECT EXISTS(
                SELECT 1 FROM events
                WHERE session_id = $1
                  AND event_type = 'input.message'
                  AND data @> $2
            )
            "#,
        )
        .bind(session_id)
        .bind(&pattern)
        .fetch_one(&self.pool)
        .await?;
        Ok(row.0)
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn list_events(
        &self,
        session_id: SessionId,
        since_sequence: Option<i32>,
        since_id: Option<EventId>,
        filter_types: &[String],
        exclude_types: &[String],
        before_sequence: Option<i32>,
        limit: Option<i32>,
    ) -> Result<Vec<EventRow>> {
        // UUID v7 is NOT guaranteed monotonically increasing across concurrent inserts,
        // so we always filter and order by the dedicated sequence column.
        // When since_id is provided, resolve it to sequence via an inline subquery (PK lookup).
        // filter_types: positive filter — when non-empty, only return matching event types.
        // exclude_types: negative filter — remove matching event types from results.
        // When both are provided, filter_types narrows first, then exclude_types removes.
        //
        // Backward pagination: when `limit` is provided (with optional `before_sequence`),
        // fetch the last N events by using ORDER BY sequence DESC LIMIT N, then reverse
        // so results are returned oldest→newest.
        if let Some(limit) = limit {
            // Backward pagination: fetch last N events before a cursor
            let rows = if let Some(before_seq) = before_sequence {
                sqlx::query_as::<_, EventRow>(
                    r#"
                    SELECT * FROM (
                        SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                        FROM events
                        WHERE session_id = $1
                          AND sequence < $2
                          AND (cardinality($3::text[]) = 0 OR event_type = ANY($3))
                          AND (cardinality($4::text[]) = 0 OR event_type <> ALL($4))
                        ORDER BY sequence DESC
                        LIMIT $5
                    ) batch
                    ORDER BY sequence ASC
                    "#,
                )
                .bind(session_id.uuid())
                .bind(before_seq)
                .bind(filter_types)
                .bind(exclude_types)
                .bind(limit as i64)
                .fetch_all(&self.pool)
                .await?
            } else {
                // No cursor: fetch the last N events
                sqlx::query_as::<_, EventRow>(
                    r#"
                    SELECT * FROM (
                        SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                        FROM events
                        WHERE session_id = $1
                          AND (cardinality($2::text[]) = 0 OR event_type = ANY($2))
                          AND (cardinality($3::text[]) = 0 OR event_type <> ALL($3))
                        ORDER BY sequence DESC
                        LIMIT $4
                    ) batch
                    ORDER BY sequence ASC
                    "#,
                )
                .bind(session_id.uuid())
                .bind(filter_types)
                .bind(exclude_types)
                .bind(limit as i64)
                .fetch_all(&self.pool)
                .await?
            };
            return Ok(rows);
        }

        // Safety-limited forward query (backward compat when no limit param).
        // Cap at 10 000 rows to prevent unbounded result sets.
        const FORWARD_SAFETY_LIMIT: i64 = 10_000;
        let rows = match (since_id, since_sequence) {
            (Some(id), _) => {
                sqlx::query_as::<_, EventRow>(
                    r#"
                    SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                    FROM events
                    WHERE session_id = $1
                      AND sequence > (SELECT sequence FROM events WHERE id = $2)
                      AND (cardinality($3::text[]) = 0 OR event_type = ANY($3))
                      AND (cardinality($4::text[]) = 0 OR event_type <> ALL($4))
                    ORDER BY sequence ASC
                    LIMIT $5
                    "#,
                )
                .bind(session_id.uuid())
                .bind(id.uuid())
                .bind(filter_types)
                .bind(exclude_types)
                .bind(FORWARD_SAFETY_LIMIT)
                .fetch_all(&self.pool)
                .await?
            }
            (None, Some(seq)) => {
                sqlx::query_as::<_, EventRow>(
                    r#"
                    SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                    FROM events
                    WHERE session_id = $1 AND sequence > $2
                      AND (cardinality($3::text[]) = 0 OR event_type = ANY($3))
                      AND (cardinality($4::text[]) = 0 OR event_type <> ALL($4))
                    ORDER BY sequence ASC
                    LIMIT $5
                    "#,
                )
                .bind(session_id.uuid())
                .bind(seq)
                .bind(filter_types)
                .bind(exclude_types)
                .bind(FORWARD_SAFETY_LIMIT)
                .fetch_all(&self.pool)
                .await?
            }
            (None, None) => {
                sqlx::query_as::<_, EventRow>(
                    r#"
                    SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                    FROM events
                    WHERE session_id = $1
                      AND (cardinality($2::text[]) = 0 OR event_type = ANY($2))
                      AND (cardinality($3::text[]) = 0 OR event_type <> ALL($3))
                    ORDER BY sequence ASC
                    LIMIT $4
                    "#,
                )
                .bind(session_id.uuid())
                .bind(filter_types)
                .bind(exclude_types)
                .bind(FORWARD_SAFETY_LIMIT)
                .fetch_all(&self.pool)
                .await?
            }
        };

        Ok(rows)
    }

    /// Advanced event listing for debugging.
    ///
    /// Supports time range, context-id filters (turn/exec/trace), tags, tool name,
    /// full-text search, around-id windowing, and direction. Builds dynamic SQL
    /// via `QueryBuilder` so filters are pushed to the database.
    ///
    /// `since_id` and `around_id` lookups are scoped to `params.session_id` so a
    /// foreign event id silently produces an empty result rather than anchoring
    /// in another session.
    ///
    /// When `order_desc` is true, rows are returned newest-first.
    pub async fn list_events_advanced(&self, params: &ListEventsParams) -> Result<Vec<EventRow>> {
        // around_id: resolve to its sequence (within this session) and return
        // [seq-window, seq+window]. Other cursors are rejected at the command
        // layer when around_id is set.
        if let Some(anchor) = params.around_id {
            const DEFAULT_WINDOW: i32 = 50;
            const MAX_WINDOW: i32 = 500;
            let window = params.window.unwrap_or(DEFAULT_WINDOW).clamp(1, MAX_WINDOW);
            let mut qb = sqlx::QueryBuilder::<sqlx::Postgres>::new(
                "WITH anchor AS (SELECT sequence FROM events WHERE id = ",
            );
            qb.push_bind(anchor.uuid());
            qb.push(" AND session_id = ");
            qb.push_bind(params.session_id.uuid());
            qb.push(") SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at FROM events WHERE session_id = ");
            qb.push_bind(params.session_id.uuid());
            qb.push(" AND sequence BETWEEN (SELECT sequence FROM anchor) - ");
            qb.push_bind(window);
            qb.push(" AND (SELECT sequence FROM anchor) + ");
            qb.push_bind(window);
            push_common_filters(&mut qb, params);
            qb.push(" ORDER BY sequence ASC LIMIT ");
            qb.push_bind((window as i64) * 2 + 1);
            return Ok(qb
                .build_query_as::<EventRow>()
                .fetch_all(&self.pool)
                .await?);
        }

        let mut qb = sqlx::QueryBuilder::<sqlx::Postgres>::new(
            "SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at FROM events WHERE session_id = ",
        );
        qb.push_bind(params.session_id.uuid());

        // since_id resolves to a sequence subquery, scoped to this session.
        // A foreign id matches no row → `sequence > NULL` is false → empty result.
        if let Some(id) = params.since_id {
            qb.push(" AND sequence > (SELECT sequence FROM events WHERE id = ");
            qb.push_bind(id.uuid());
            qb.push(" AND session_id = ");
            qb.push_bind(params.session_id.uuid());
            qb.push(")");
        }
        if let Some(seq) = params.after_sequence {
            qb.push(" AND sequence > ");
            qb.push_bind(seq);
        }
        if let Some(seq) = params.before_sequence {
            qb.push(" AND sequence < ");
            qb.push_bind(seq);
        }

        push_common_filters(&mut qb, params);

        if params.order_desc {
            qb.push(" ORDER BY sequence DESC LIMIT ");
        } else {
            qb.push(" ORDER BY sequence ASC LIMIT ");
        }
        let limit = params.limit.unwrap_or(1_000).clamp(1, 10_000);
        qb.push_bind(limit as i64);

        Ok(qb
            .build_query_as::<EventRow>()
            .fetch_all(&self.pool)
            .await?)
    }

    /// One-shot debug summary: per-type counts + first/last timestamps.
    pub async fn events_summary(&self, session_id: SessionId) -> Result<EventsSummary> {
        type SummaryRow = (String, i64, Option<DateTime<Utc>>, Option<DateTime<Utc>>);
        let rows: Vec<SummaryRow> = sqlx::query_as(
            r#"
                SELECT event_type, COUNT(*)::bigint, MIN(ts), MAX(ts)
                FROM events
                WHERE session_id = $1
                GROUP BY event_type
                ORDER BY event_type ASC
                "#,
        )
        .bind(session_id.uuid())
        .fetch_all(&self.pool)
        .await?;

        let mut summary = EventsSummary::default();
        for (event_type, count, min_ts, max_ts) in rows {
            summary.total += count;
            if let Some(t) = min_ts {
                summary.first_ts = Some(match summary.first_ts {
                    Some(prev) if prev < t => prev,
                    _ => t,
                });
            }
            if let Some(t) = max_ts {
                summary.last_ts = Some(match summary.last_ts {
                    Some(prev) if prev > t => prev,
                    _ => t,
                });
            }
            summary.by_type.push(EventTypeCount { event_type, count });
        }
        Ok(summary)
    }

    /// Count events for a session using SELECT COUNT(*) — no row materialization.
    /// When `exclude_types` is non-empty, excludes matching event types from the count.
    pub async fn count_events(
        &self,
        session_id: SessionId,
        exclude_types: &[String],
    ) -> Result<i64> {
        let (count,): (i64,) = sqlx::query_as(
            r#"
            SELECT COUNT(*)
            FROM events
            WHERE session_id = $1
              AND (cardinality($2::text[]) = 0 OR event_type <> ALL($2))
            "#,
        )
        .bind(session_id.uuid())
        .bind(exclude_types)
        .fetch_one(&self.pool)
        .await?;

        Ok(count)
    }

    /// Find the nearest turn.started sequence at or before the given sequence.
    /// Used for turn boundary snapping in pagination.
    pub async fn find_turn_boundary(
        &self,
        session_id: SessionId,
        before_sequence: i32,
    ) -> Result<Option<i32>> {
        let row: Option<(i32,)> = sqlx::query_as(
            r#"
            SELECT sequence
            FROM events
            WHERE session_id = $1
              AND sequence <= $2
              AND event_type = 'turn.started'
            ORDER BY sequence DESC
            LIMIT 1
            "#,
        )
        .bind(session_id.uuid())
        .bind(before_sequence)
        .fetch_optional(&self.pool)
        .await?;
        Ok(row.map(|r| r.0))
    }

    /// List only message events for a session (for MessageStore implementation)
    ///
    /// Returns events with types: input.message, output.message.completed, tool.completed
    /// Ordered by sequence for conversation reconstruction.
    /// Note: Tool calls are embedded in output.message.completed events via ContentPart::ToolCall.
    /// Note: Tool results come from tool.completed events (not message.tool_result).
    pub async fn list_message_events(&self, session_id: SessionId) -> Result<Vec<EventRow>> {
        self.list_message_events_limited(session_id, None).await
    }

    /// List message events with an optional limit.
    /// When `limit` is Some, returns the most recent N messages (by sequence)
    /// in ascending order for correct conversation reconstruction.
    pub async fn list_message_events_limited(
        &self,
        session_id: SessionId,
        limit: Option<i32>,
    ) -> Result<Vec<EventRow>> {
        let started = std::time::Instant::now();
        let rows = if let Some(limit) = limit.filter(|limit| *limit > 0) {
            // Subquery: get most recent N by sequence DESC, then re-order ASC
            sqlx::query_as::<_, EventRow>(
                r#"
                SELECT * FROM (
                    SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                    FROM events
                    WHERE session_id = $1
                      AND event_type IN ('input.message', 'output.message.completed', 'tool.completed')
                    ORDER BY sequence DESC
                    LIMIT $2
                ) recent
                ORDER BY sequence ASC
                "#,
            )
            .bind(session_id.uuid())
            .bind(limit as i64)
            .fetch_all(&self.pool)
            .await?
        } else if limit.is_some() {
            Vec::new()
        } else {
            // Safety cap when no explicit limit — prevents unbounded result sets
            // and keeps the latest prompt-relevant rows.
            sqlx::query_as::<_, EventRow>(
                r#"
                SELECT * FROM (
                    SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                    FROM events
                    WHERE session_id = $1
                      AND event_type IN ('input.message', 'output.message.completed', 'tool.completed')
                    ORDER BY sequence DESC
                    LIMIT $2
                ) recent
                ORDER BY sequence ASC
                "#,
            )
            .bind(session_id.uuid())
            .bind(MESSAGE_SAFETY_LIMIT as i64)
            .fetch_all(&self.pool)
            .await?
        };

        let effective_limit = limit
            .filter(|limit| *limit > 0)
            .map(i64::from)
            .unwrap_or(MESSAGE_SAFETY_LIMIT as i64);
        maybe_warn_slow_message_history(
            MESSAGE_HISTORY_EVENTS,
            started.elapsed(),
            rows.len() as u64,
            effective_limit,
        );

        Ok(rows)
    }

    /// Count message events for a session using SELECT COUNT(*) — no row materialization.
    pub async fn count_message_events(&self, session_id: SessionId) -> Result<i64> {
        let (count,): (i64,) = sqlx::query_as(
            r#"
            SELECT COUNT(*)
            FROM events
            WHERE session_id = $1
              AND event_type IN ('input.message', 'output.message.completed', 'tool.completed')
            "#,
        )
        .bind(session_id.uuid())
        .fetch_one(&self.pool)
        .await?;
        Ok(count)
    }

    /// List message events for a session with filters applied.
    ///
    /// This method builds a dynamic SQL query based on the provided filters.
    /// DB-mappable filters (TimeRange, EventTypes, ToolName, Search, etc.) are
    /// pushed to the database for efficient filtering. Custom filters are applied
    /// in-memory after loading.
    ///
    /// Note: Injections are NOT applied here - they should be applied at the
    /// MessageRetriever layer after converting events to messages.
    pub async fn list_message_events_filtered(
        &self,
        query: &MessageQuery,
    ) -> Result<Vec<EventRow>> {
        let started = std::time::Instant::now();
        // Build dynamic SQL query
        let mut sql = String::from(
            "SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at FROM events WHERE session_id = $1",
        );

        // Collect bound values for later binding
        // We track types separately since sqlx needs typed bindings
        let mut time_from: Option<DateTime<Utc>> = None;
        let mut time_to: Option<DateTime<Utc>> = None;
        let mut event_types: Option<Vec<String>> = None;
        let mut tool_name: Option<String> = None;
        let mut search_query: Option<String> = None;
        let mut exclude_ids: Option<Vec<Uuid>> = None;
        let mut include_ids: Option<Vec<Uuid>> = None;

        // Check for EventTypes filter, else use defaults
        for filter in &query.filters {
            if let MessageFilter::EventTypes(types) = filter {
                event_types = Some(types.clone());
                break;
            }
        }

        // Default event types if not specified
        let types = event_types.unwrap_or_else(|| {
            vec![
                "input.message".to_string(),
                "output.message.completed".to_string(),
                "tool.completed".to_string(),
            ]
        });
        sql.push_str(" AND event_type = ANY($2)");

        // Build parameter index tracker (starting at 3 since $1=session_id, $2=event_types)
        let mut param_idx = 3;
        if query.after_sequence.is_some() {
            sql.push_str(&format!(" AND sequence > ${param_idx}"));
            param_idx += 1;
        }

        // Process filters
        for filter in &query.filters {
            match filter {
                MessageFilter::EventTypes(_) => {
                    // Already handled above
                }
                MessageFilter::TimeRange { from, to } => {
                    if let Some(f) = from {
                        sql.push_str(&format!(" AND created_at >= ${}", param_idx));
                        time_from = Some(*f);
                        param_idx += 1;
                    }
                    if let Some(t) = to {
                        sql.push_str(&format!(" AND created_at <= ${}", param_idx));
                        time_to = Some(*t);
                        param_idx += 1;
                    }
                }
                MessageFilter::ToolName(name) => {
                    sql.push_str(&format!(
                        " AND (event_type = 'tool.completed' AND data->>'tool_name' = ${})",
                        param_idx
                    ));
                    tool_name = Some(name.clone());
                    param_idx += 1;
                }
                MessageFilter::Search(q) => {
                    sql.push_str(&format!(
                        " AND search_vector @@ plainto_tsquery('english', ${})",
                        param_idx
                    ));
                    search_query = Some(q.clone());
                    param_idx += 1;
                }
                MessageFilter::ExcludeIds(ids) => {
                    sql.push_str(&format!(" AND id != ALL(${})", param_idx));
                    exclude_ids = Some(ids.iter().map(|id| id.uuid()).collect());
                    param_idx += 1;
                }
                MessageFilter::IncludeIds(ids) => {
                    sql.push_str(&format!(" AND id = ANY(${})", param_idx));
                    include_ids = Some(ids.iter().map(|id| id.uuid()).collect());
                    param_idx += 1;
                }
                MessageFilter::Custom(_) => {
                    // Custom filters are applied in-memory, not in SQL
                }
            }
        }

        let keep_head = query.keep_head.unwrap_or(0);
        // Whether the final SQL emits rows newest-first (needs reversing back to
        // chronological order after fetch).
        let mut needs_reverse = false;
        let effective_limit: i64;
        match (query.offset, query.limit) {
            (Some(offset), Some(limit)) => {
                effective_limit = limit.max(0);
                sql = format!(
                    "SELECT * FROM ({sql} ORDER BY sequence ASC OFFSET {}) offset_events ORDER BY sequence DESC LIMIT {}",
                    offset.max(0),
                    limit.max(0)
                );
                needs_reverse = true;
            }
            (Some(offset), None) => {
                effective_limit = -1;
                sql.push_str(&format!(" ORDER BY sequence ASC OFFSET {}", offset.max(0)));
            }
            (None, Some(limit)) if keep_head > 0 => {
                effective_limit = keep_head as i64 + limit.max(0);
                // Head+tail load: keep the first `keep_head` (the task anchor) plus
                // the latest `limit` tail, de-duplicated when the windows overlap.
                //
                // Select each end with an index-friendly `ORDER BY sequence … LIMIT`
                // over the (session_id, sequence) index — early-terminating after
                // keep_head / limit rows — then UNION on `id` (avoids equality on
                // jsonb columns) and fetch the full rows by primary key. This keeps
                // the common candidate load at O(keep_head + limit), not
                // O(total_history): infinity_context sets keep_head > 0 on every
                // load, so a full-history window sort here would scale with the
                // entire conversation. The base query is inlined into each end
                // (rather than a multiply-referenced CTE, which Postgres would
                // materialize and full-scan) so both ends keep the index. Bound
                // parameters are referenced by number, so repeating the SQL text
                // reuses the same bindings.
                sql = format!(
                    "SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at \
                     FROM events WHERE id IN (\
                       (SELECT id FROM ({sql}) head_q ORDER BY sequence ASC LIMIT {}) \
                       UNION \
                       (SELECT id FROM ({sql}) tail_q ORDER BY sequence DESC LIMIT {})\
                     ) ORDER BY sequence ASC",
                    keep_head as i64,
                    limit.max(0)
                );
            }
            (None, Some(limit)) => {
                effective_limit = limit.max(0);
                sql.push_str(&format!(" ORDER BY sequence DESC LIMIT {}", limit.max(0)));
                needs_reverse = true;
            }
            (None, None) => {
                effective_limit = MESSAGE_SAFETY_LIMIT as i64;
                // Safety cap on the otherwise-unbounded full-history read. This
                // branch is reached when MessageRetriever::load_filtered forces
                // limit/offset = None to fetch the full candidate set for
                // in-memory custom filtering / exact-count windowing. Without a
                // cap this deserializes every JSONB row for the whole session,
                // O(total_history) per call. The cap keeps the most recent N
                // rows (DESC + reverse) so the prompt window stays anchored to
                // recent history, mirroring the identical MESSAGE_SAFETY_LIMIT
                // already applied on the sibling list_message_events_limited
                // path (line ~508). Callers wanting a precise window pass an
                // explicit limit, which takes the bounded branches above.
                sql.push_str(&format!(
                    " ORDER BY sequence DESC LIMIT {}",
                    MESSAGE_SAFETY_LIMIT
                ));
                needs_reverse = true;
            }
        }

        // Build and execute query with dynamic bindings
        // sqlx doesn't support truly dynamic queries, so we need to use raw SQL
        // with all possible parameters, binding None for unused ones
        let mut db_query = sqlx::query_as::<_, EventRow>(sqlx::AssertSqlSafe(sql.as_str()))
            .bind(query.session_id.uuid())
            .bind(&types);

        if let Some(after_sequence) = query.after_sequence {
            db_query = db_query.bind(after_sequence);
        }

        // Bind parameters in order they were added to SQL
        if time_from.is_some() {
            db_query = db_query.bind(time_from);
        }
        if time_to.is_some() {
            db_query = db_query.bind(time_to);
        }
        if tool_name.is_some() {
            db_query = db_query.bind(tool_name);
        }
        if search_query.is_some() {
            db_query = db_query.bind(search_query);
        }
        if exclude_ids.is_some() {
            db_query = db_query.bind(exclude_ids);
        }
        if include_ids.is_some() {
            db_query = db_query.bind(include_ids);
        }
        let mut rows = db_query.fetch_all(&self.pool).await?;
        if needs_reverse {
            rows.reverse();
        }
        maybe_warn_slow_message_history(
            FILTERED_MESSAGE_HISTORY_EVENTS,
            started.elapsed(),
            rows.len() as u64,
            effective_limit,
        );

        Ok(rows)
    }

    /// Get preview text for multiple sessions
    ///
    /// Returns a map of session_id -> preview text (first 200 chars of first user message)
    /// This is an efficient batch query that gets previews for all provided session IDs.
    pub async fn get_session_previews(
        &self,
        session_ids: &[Uuid],
    ) -> Result<std::collections::HashMap<Uuid, String>> {
        if session_ids.is_empty() {
            return Ok(std::collections::HashMap::new());
        }

        // Use DISTINCT ON to get the first user message for each session
        // Extract text content from the JSON data structure
        let rows: Vec<(Uuid, String)> = sqlx::query_as(
            r#"
            WITH first_messages AS (
                SELECT DISTINCT ON (session_id)
                    session_id,
                    data
                FROM events
                WHERE session_id = ANY($1)
                  AND event_type = 'input.message'
                ORDER BY session_id, sequence ASC
            )
            SELECT
                session_id,
                LEFT(
                    COALESCE(
                        -- Extract text from content array: [{"type": "text", "text": "..."}]
                        data->'message'->'content'->0->>'text',
                        -- Fallback: try direct text field
                        data->'message'->>'text',
                        ''
                    ),
                    200
                ) as preview
            FROM first_messages
            WHERE data->'message'->'content'->0->>'text' IS NOT NULL
               OR data->'message'->>'text' IS NOT NULL
            "#,
        )
        .bind(session_ids)
        .fetch_all(&self.pool)
        .await?;

        Ok(rows.into_iter().collect())
    }

    /// Get output preview text for multiple sessions
    ///
    /// Returns a map of session_id -> preview text (first 200 chars of last agent message)
    /// This is an efficient batch query that gets output previews for all provided session IDs.
    pub async fn get_session_output_previews(
        &self,
        session_ids: &[Uuid],
    ) -> Result<std::collections::HashMap<Uuid, String>> {
        if session_ids.is_empty() {
            return Ok(std::collections::HashMap::new());
        }

        // Use DISTINCT ON with DESC order to get the last agent message for each session
        // Extract text content from the JSON data structure
        let rows: Vec<(Uuid, String)> = sqlx::query_as(
            r#"
            WITH last_messages AS (
                SELECT DISTINCT ON (session_id)
                    session_id,
                    data
                FROM events
                WHERE session_id = ANY($1)
                  AND event_type = 'output.message.completed'
                ORDER BY session_id, sequence DESC
            )
            SELECT
                session_id,
                LEFT(
                    COALESCE(
                        -- Extract text from content array: [{"type": "text", "text": "..."}]
                        data->'message'->'content'->0->>'text',
                        -- Fallback: try direct text field
                        data->'message'->>'text',
                        ''
                    ),
                    200
                ) as preview
            FROM last_messages
            WHERE data->'message'->'content'->0->>'text' IS NOT NULL
               OR data->'message'->>'text' IS NOT NULL
            "#,
        )
        .bind(session_ids)
        .fetch_all(&self.pool)
        .await?;

        Ok(rows.into_iter().collect())
    }
}
