// PostgreSQL repository: Events (source of truth for messages)

use super::super::models::*;
use super::Database;
use anyhow::Result;
use chrono::{DateTime, Utc};
use everruns_core::message_filter::{MessageFilter, MessageQuery};
use everruns_core::typed_id::{EventId, SessionId};
use uuid::Uuid;

impl Database {
    // ============================================
    // Events (source of truth for messages)
    // ============================================
    //
    // Messages are stored as events with type "message.*"
    // Use list_message_events() to load conversation messages.

    pub async fn create_event(&self, input: CreateEventRow) -> Result<EventRow> {
        // Atomically allocate next sequence number for this session
        // ID is generated by database using uuidv7() for monotonically increasing UUIDs
        let row = sqlx::query_as::<_, EventRow>(
            r#"
            INSERT INTO events (session_id, sequence, event_type, ts, context, data, metadata, tags)
            VALUES ($1, allocate_event_sequence($1), $2, $3, $4, $5, $6, $7)
            RETURNING id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
            "#,
        )
        .bind(input.session_id)
        .bind(&input.event_type)
        .bind(input.ts)
        .bind(&input.context)
        .bind(&input.data)
        .bind(&input.metadata)
        .bind(&input.tags)
        .fetch_one(&self.pool)
        .await?;

        Ok(row)
    }

    /// Check if an input.message event with a given slack_ts already exists in a session.
    /// Used for dedup when Slack sends duplicate events (app_mention + message).
    pub async fn has_event_with_slack_ts(
        &self,
        session_id: SessionId,
        slack_ts: &str,
    ) -> Result<bool> {
        let pattern = serde_json::json!({
            "message": { "metadata": { "slack_ts": slack_ts } }
        });
        let row: (bool,) = sqlx::query_as(
            r#"
            SELECT EXISTS(
                SELECT 1 FROM events
                WHERE session_id = $1
                  AND event_type = 'input.message'
                  AND data @> $2
            )
            "#,
        )
        .bind(session_id)
        .bind(&pattern)
        .fetch_one(&self.pool)
        .await?;
        Ok(row.0)
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn list_events(
        &self,
        session_id: SessionId,
        since_sequence: Option<i32>,
        since_id: Option<EventId>,
        filter_types: &[String],
        exclude_types: &[String],
        before_sequence: Option<i32>,
        limit: Option<i32>,
    ) -> Result<Vec<EventRow>> {
        // UUID v7 is NOT guaranteed monotonically increasing across concurrent inserts,
        // so we always filter and order by the dedicated sequence column.
        // When since_id is provided, resolve it to sequence via an inline subquery (PK lookup).
        // filter_types: positive filter — when non-empty, only return matching event types.
        // exclude_types: negative filter — remove matching event types from results.
        // When both are provided, filter_types narrows first, then exclude_types removes.
        //
        // Backward pagination: when `limit` is provided (with optional `before_sequence`),
        // fetch the last N events by using ORDER BY sequence DESC LIMIT N, then reverse
        // so results are returned oldest→newest.
        if let Some(limit) = limit {
            // Backward pagination: fetch last N events before a cursor
            let rows = if let Some(before_seq) = before_sequence {
                sqlx::query_as::<_, EventRow>(
                    r#"
                    SELECT * FROM (
                        SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                        FROM events
                        WHERE session_id = $1
                          AND sequence < $2
                          AND (cardinality($3::text[]) = 0 OR event_type = ANY($3))
                          AND (cardinality($4::text[]) = 0 OR event_type <> ALL($4))
                        ORDER BY sequence DESC
                        LIMIT $5
                    ) batch
                    ORDER BY sequence ASC
                    "#,
                )
                .bind(session_id.uuid())
                .bind(before_seq)
                .bind(filter_types)
                .bind(exclude_types)
                .bind(limit as i64)
                .fetch_all(&self.pool)
                .await?
            } else {
                // No cursor: fetch the last N events
                sqlx::query_as::<_, EventRow>(
                    r#"
                    SELECT * FROM (
                        SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                        FROM events
                        WHERE session_id = $1
                          AND (cardinality($2::text[]) = 0 OR event_type = ANY($2))
                          AND (cardinality($3::text[]) = 0 OR event_type <> ALL($3))
                        ORDER BY sequence DESC
                        LIMIT $4
                    ) batch
                    ORDER BY sequence ASC
                    "#,
                )
                .bind(session_id.uuid())
                .bind(filter_types)
                .bind(exclude_types)
                .bind(limit as i64)
                .fetch_all(&self.pool)
                .await?
            };
            return Ok(rows);
        }

        // Safety-limited forward query (backward compat when no limit param).
        // Cap at 10 000 rows to prevent unbounded result sets.
        const FORWARD_SAFETY_LIMIT: i64 = 10_000;
        let rows = match (since_id, since_sequence) {
            (Some(id), _) => {
                sqlx::query_as::<_, EventRow>(
                    r#"
                    SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                    FROM events
                    WHERE session_id = $1
                      AND sequence > (SELECT sequence FROM events WHERE id = $2)
                      AND (cardinality($3::text[]) = 0 OR event_type = ANY($3))
                      AND (cardinality($4::text[]) = 0 OR event_type <> ALL($4))
                    ORDER BY sequence ASC
                    LIMIT $5
                    "#,
                )
                .bind(session_id.uuid())
                .bind(id.uuid())
                .bind(filter_types)
                .bind(exclude_types)
                .bind(FORWARD_SAFETY_LIMIT)
                .fetch_all(&self.pool)
                .await?
            }
            (None, Some(seq)) => {
                sqlx::query_as::<_, EventRow>(
                    r#"
                    SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                    FROM events
                    WHERE session_id = $1 AND sequence > $2
                      AND (cardinality($3::text[]) = 0 OR event_type = ANY($3))
                      AND (cardinality($4::text[]) = 0 OR event_type <> ALL($4))
                    ORDER BY sequence ASC
                    LIMIT $5
                    "#,
                )
                .bind(session_id.uuid())
                .bind(seq)
                .bind(filter_types)
                .bind(exclude_types)
                .bind(FORWARD_SAFETY_LIMIT)
                .fetch_all(&self.pool)
                .await?
            }
            (None, None) => {
                sqlx::query_as::<_, EventRow>(
                    r#"
                    SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                    FROM events
                    WHERE session_id = $1
                      AND (cardinality($2::text[]) = 0 OR event_type = ANY($2))
                      AND (cardinality($3::text[]) = 0 OR event_type <> ALL($3))
                    ORDER BY sequence ASC
                    LIMIT $4
                    "#,
                )
                .bind(session_id.uuid())
                .bind(filter_types)
                .bind(exclude_types)
                .bind(FORWARD_SAFETY_LIMIT)
                .fetch_all(&self.pool)
                .await?
            }
        };

        Ok(rows)
    }

    /// Count events for a session using SELECT COUNT(*) — no row materialization.
    /// When `exclude_types` is non-empty, excludes matching event types from the count.
    pub async fn count_events(
        &self,
        session_id: SessionId,
        exclude_types: &[String],
    ) -> Result<i64> {
        let (count,): (i64,) = sqlx::query_as(
            r#"
            SELECT COUNT(*)
            FROM events
            WHERE session_id = $1
              AND (cardinality($2::text[]) = 0 OR event_type <> ALL($2))
            "#,
        )
        .bind(session_id.uuid())
        .bind(exclude_types)
        .fetch_one(&self.pool)
        .await?;

        Ok(count)
    }

    /// Find the nearest turn.started sequence at or before the given sequence.
    /// Used for turn boundary snapping in pagination.
    pub async fn find_turn_boundary(
        &self,
        session_id: SessionId,
        before_sequence: i32,
    ) -> Result<Option<i32>> {
        let row: Option<(i32,)> = sqlx::query_as(
            r#"
            SELECT sequence
            FROM events
            WHERE session_id = $1
              AND sequence <= $2
              AND event_type = 'turn.started'
            ORDER BY sequence DESC
            LIMIT 1
            "#,
        )
        .bind(session_id.uuid())
        .bind(before_sequence)
        .fetch_optional(&self.pool)
        .await?;
        Ok(row.map(|r| r.0))
    }

    /// List only message events for a session (for MessageStore implementation)
    ///
    /// Returns events with types: input.message, output.message.completed, tool.completed
    /// Ordered by sequence for conversation reconstruction.
    /// Note: Tool calls are embedded in output.message.completed events via ContentPart::ToolCall.
    /// Note: Tool results come from tool.completed events (not message.tool_result).
    pub async fn list_message_events(&self, session_id: SessionId) -> Result<Vec<EventRow>> {
        self.list_message_events_limited(session_id, None).await
    }

    /// List message events with an optional limit.
    /// When `limit` is Some, returns the most recent N messages (by sequence)
    /// in ascending order for correct conversation reconstruction.
    pub async fn list_message_events_limited(
        &self,
        session_id: SessionId,
        limit: Option<i32>,
    ) -> Result<Vec<EventRow>> {
        let rows = if let Some(limit) = limit {
            // Subquery: get most recent N by sequence DESC, then re-order ASC
            sqlx::query_as::<_, EventRow>(
                r#"
                SELECT * FROM (
                    SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                    FROM events
                    WHERE session_id = $1
                      AND event_type IN ('input.message', 'output.message.completed', 'tool.completed')
                    ORDER BY sequence DESC
                    LIMIT $2
                ) recent
                ORDER BY sequence ASC
                "#,
            )
            .bind(session_id.uuid())
            .bind(limit as i64)
            .fetch_all(&self.pool)
            .await?
        } else {
            // Safety cap when no explicit limit — prevents unbounded result sets.
            const MESSAGE_SAFETY_LIMIT: i64 = 5_000;
            sqlx::query_as::<_, EventRow>(
                r#"
                SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at
                FROM events
                WHERE session_id = $1
                  AND event_type IN ('input.message', 'output.message.completed', 'tool.completed')
                ORDER BY sequence ASC
                LIMIT $2
                "#,
            )
            .bind(session_id.uuid())
            .bind(MESSAGE_SAFETY_LIMIT)
            .fetch_all(&self.pool)
            .await?
        };

        Ok(rows)
    }

    /// Count message events for a session using SELECT COUNT(*) — no row materialization.
    pub async fn count_message_events(&self, session_id: SessionId) -> Result<i64> {
        let (count,): (i64,) = sqlx::query_as(
            r#"
            SELECT COUNT(*)
            FROM events
            WHERE session_id = $1
              AND event_type IN ('input.message', 'output.message.completed', 'tool.completed')
            "#,
        )
        .bind(session_id.uuid())
        .fetch_one(&self.pool)
        .await?;
        Ok(count)
    }

    /// List message events for a session with filters applied.
    ///
    /// This method builds a dynamic SQL query based on the provided filters.
    /// DB-mappable filters (TimeRange, EventTypes, ToolName, Search, etc.) are
    /// pushed to the database for efficient filtering. Custom filters are applied
    /// in-memory after loading.
    ///
    /// Note: Injections are NOT applied here - they should be applied at the
    /// MessageRetriever layer after converting events to messages.
    pub async fn list_message_events_filtered(
        &self,
        query: &MessageQuery,
    ) -> Result<Vec<EventRow>> {
        // Build dynamic SQL query
        let mut sql = String::from(
            "SELECT id, session_id, sequence, event_type, ts, context, data, metadata, tags, created_at FROM events WHERE session_id = $1",
        );

        // Collect bound values for later binding
        // We track types separately since sqlx needs typed bindings
        let mut time_from: Option<DateTime<Utc>> = None;
        let mut time_to: Option<DateTime<Utc>> = None;
        let mut event_types: Option<Vec<String>> = None;
        let mut tool_name: Option<String> = None;
        let mut search_query: Option<String> = None;
        let mut exclude_ids: Option<Vec<Uuid>> = None;
        let mut include_ids: Option<Vec<Uuid>> = None;

        // Check for EventTypes filter, else use defaults
        for filter in &query.filters {
            if let MessageFilter::EventTypes(types) = filter {
                event_types = Some(types.clone());
                break;
            }
        }

        // Default event types if not specified
        let types = event_types.unwrap_or_else(|| {
            vec![
                "input.message".to_string(),
                "output.message.completed".to_string(),
                "tool.completed".to_string(),
            ]
        });
        sql.push_str(" AND event_type = ANY($2)");

        // Build parameter index tracker (starting at 3 since $1=session_id, $2=event_types)
        let mut param_idx = 3;

        // Process filters
        for filter in &query.filters {
            match filter {
                MessageFilter::EventTypes(_) => {
                    // Already handled above
                }
                MessageFilter::TimeRange { from, to } => {
                    if let Some(f) = from {
                        sql.push_str(&format!(" AND created_at >= ${}", param_idx));
                        time_from = Some(*f);
                        param_idx += 1;
                    }
                    if let Some(t) = to {
                        sql.push_str(&format!(" AND created_at <= ${}", param_idx));
                        time_to = Some(*t);
                        param_idx += 1;
                    }
                }
                MessageFilter::ToolName(name) => {
                    sql.push_str(&format!(
                        " AND (event_type = 'tool.completed' AND data->>'tool_name' = ${})",
                        param_idx
                    ));
                    tool_name = Some(name.clone());
                    param_idx += 1;
                }
                MessageFilter::Search(q) => {
                    sql.push_str(&format!(
                        " AND search_vector @@ plainto_tsquery('english', ${})",
                        param_idx
                    ));
                    search_query = Some(q.clone());
                    param_idx += 1;
                }
                MessageFilter::ExcludeIds(ids) => {
                    sql.push_str(&format!(" AND id != ALL(${})", param_idx));
                    exclude_ids = Some(ids.iter().map(|id| id.uuid()).collect());
                    param_idx += 1;
                }
                MessageFilter::IncludeIds(ids) => {
                    sql.push_str(&format!(" AND id = ANY(${})", param_idx));
                    include_ids = Some(ids.iter().map(|id| id.uuid()).collect());
                    param_idx += 1;
                }
                MessageFilter::Custom(_) => {
                    // Custom filters are applied in-memory, not in SQL
                }
            }
        }

        sql.push_str(" ORDER BY sequence ASC");

        // Apply limit/offset
        if let Some(limit) = query.limit {
            sql.push_str(&format!(" LIMIT {}", limit));
        }
        if let Some(offset) = query.offset {
            sql.push_str(&format!(" OFFSET {}", offset));
        }

        // Build and execute query with dynamic bindings
        // sqlx doesn't support truly dynamic queries, so we need to use raw SQL
        // with all possible parameters, binding None for unused ones
        let mut db_query = sqlx::query_as::<_, EventRow>(&sql)
            .bind(query.session_id.uuid())
            .bind(&types);

        // Bind parameters in order they were added to SQL
        if time_from.is_some() {
            db_query = db_query.bind(time_from);
        }
        if time_to.is_some() {
            db_query = db_query.bind(time_to);
        }
        if tool_name.is_some() {
            db_query = db_query.bind(tool_name);
        }
        if search_query.is_some() {
            db_query = db_query.bind(search_query);
        }
        if exclude_ids.is_some() {
            db_query = db_query.bind(exclude_ids);
        }
        if include_ids.is_some() {
            db_query = db_query.bind(include_ids);
        }

        let rows = db_query.fetch_all(&self.pool).await?;

        Ok(rows)
    }

    /// Get preview text for multiple sessions
    ///
    /// Returns a map of session_id -> preview text (first 200 chars of first user message)
    /// This is an efficient batch query that gets previews for all provided session IDs.
    pub async fn get_session_previews(
        &self,
        session_ids: &[Uuid],
    ) -> Result<std::collections::HashMap<Uuid, String>> {
        if session_ids.is_empty() {
            return Ok(std::collections::HashMap::new());
        }

        // Use DISTINCT ON to get the first user message for each session
        // Extract text content from the JSON data structure
        let rows: Vec<(Uuid, String)> = sqlx::query_as(
            r#"
            WITH first_messages AS (
                SELECT DISTINCT ON (session_id)
                    session_id,
                    data
                FROM events
                WHERE session_id = ANY($1)
                  AND event_type = 'input.message'
                ORDER BY session_id, sequence ASC
            )
            SELECT
                session_id,
                LEFT(
                    COALESCE(
                        -- Extract text from content array: [{"type": "text", "text": "..."}]
                        data->'message'->'content'->0->>'text',
                        -- Fallback: try direct text field
                        data->'message'->>'text',
                        ''
                    ),
                    200
                ) as preview
            FROM first_messages
            WHERE data->'message'->'content'->0->>'text' IS NOT NULL
               OR data->'message'->>'text' IS NOT NULL
            "#,
        )
        .bind(session_ids)
        .fetch_all(&self.pool)
        .await?;

        Ok(rows.into_iter().collect())
    }

    /// Get output preview text for multiple sessions
    ///
    /// Returns a map of session_id -> preview text (first 200 chars of last agent message)
    /// This is an efficient batch query that gets output previews for all provided session IDs.
    pub async fn get_session_output_previews(
        &self,
        session_ids: &[Uuid],
    ) -> Result<std::collections::HashMap<Uuid, String>> {
        if session_ids.is_empty() {
            return Ok(std::collections::HashMap::new());
        }

        // Use DISTINCT ON with DESC order to get the last agent message for each session
        // Extract text content from the JSON data structure
        let rows: Vec<(Uuid, String)> = sqlx::query_as(
            r#"
            WITH last_messages AS (
                SELECT DISTINCT ON (session_id)
                    session_id,
                    data
                FROM events
                WHERE session_id = ANY($1)
                  AND event_type = 'output.message.completed'
                ORDER BY session_id, sequence DESC
            )
            SELECT
                session_id,
                LEFT(
                    COALESCE(
                        -- Extract text from content array: [{"type": "text", "text": "..."}]
                        data->'message'->'content'->0->>'text',
                        -- Fallback: try direct text field
                        data->'message'->>'text',
                        ''
                    ),
                    200
                ) as preview
            FROM last_messages
            WHERE data->'message'->'content'->0->>'text' IS NOT NULL
               OR data->'message'->>'text' IS NOT NULL
            "#,
        )
        .bind(session_ids)
        .fetch_all(&self.pool)
        .await?;

        Ok(rows.into_iter().collect())
    }
}
