// OpenAPI specification generation
//
// This module defines the OpenAPI spec for the Everruns API.
// It can be used by both the main API server (for Swagger UI)
// and the export-openapi binary (for static spec generation).

use crate::api;
use crate::api::{ListResponse, PaginatedResponse};
use crate::domains;
use crate::kernel_imports::{
    CapabilityInfo, ContextReportContribution, ContextReportSection, Event, EventContext,
    EventData, FileInfo, FileStat, GrepMatch, GrepResult, LeasedResource, McpServer,
    McpServerStatus, McpServerTransportType, SessionContextReport, SessionFile, Skill,
    SkillContent, SkillFileEntry, SkillSourceType, SkillStatus, SkillValidationResult,
    events::{
        ActCompletedData, ActStartedData, InputMessageData, LlmGenerationData,
        LlmGenerationMetadata, LlmGenerationOutput, ModelMetadata, OutputMessageCompletedData,
        OutputMessageDeltaData, OutputMessageStartedData, ReasonCompletedData, ReasonStartedData,
        SessionModelChangedData, SessionStartedData, TokenUsage, ToolCallSummary,
        ToolCompletedData, ToolStartedData, TurnCompletedData, TurnFailedData, TurnSealedData,
        TurnStartedData,
    },
    everruns_provider::model::Model,
    everruns_provider::model::ModelWithProvider,
    everruns_provider::provider::DriverId,
    everruns_provider::provider::ProviderStatus,
    everruns_provider::tool_types::ToolCall,
};
use everruns_platform::{Agent, AgentStatus};
use everruns_platform::{Session, SessionStatus};
use everruns_provider::provider::{
    Provider, ProviderRequestHeader, ProviderRequestOptions, ProviderTraceConfig,
};
use serde_json::json;
use utoipa::openapi::extensions::Extensions;
use utoipa::openapi::{RefOr, Schema};
use utoipa::{Modify, OpenApi};

const SDK_RESPONSE_WRAPPERS: &[(&str, &str, &str)] = &[
    ("WithUrls_Agent", "resource", "Agent"),
    ("WithUrls_AgentWithCounts", "resource", "Agent"),
    ("WithUrls_Session", "resource", "Session"),
    ("WithUrls_CapabilityInfo", "resource", "CapabilityInfo"),
    (
        "PaginatedResponse_WithUrls_AgentWithCounts",
        "list",
        "Agent",
    ),
    ("PaginatedResponse_WithUrls_Session", "list", "Session"),
    (
        "PaginatedResponse_WithUrls_CapabilityInfo",
        "list",
        "CapabilityInfo",
    ),
];

struct SdkMetadata;

impl Modify for SdkMetadata {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let Some(components) = openapi.components.as_mut() else {
            return;
        };

        for &(wrapper, kind, model) in SDK_RESPONSE_WRAPPERS {
            let Some(RefOr::T(schema)) = components.schemas.get_mut(wrapper) else {
                continue;
            };
            let Some(extensions) = schema_extensions_mut(schema) else {
                continue;
            };
            let extensions = extensions.get_or_insert_with(Extensions::default);
            extensions.insert(
                "x-sdk-response-wrapper".to_string(),
                json!({
                    "kind": kind,
                    "model": format!("#/components/schemas/{model}"),
                }),
            );
        }
    }
}

fn schema_extensions_mut(schema: &mut Schema) -> Option<&mut Option<Extensions>> {
    match schema {
        Schema::Array(schema) => Some(&mut schema.extensions),
        Schema::Object(schema) => Some(&mut schema.extensions),
        Schema::OneOf(schema) => Some(&mut schema.extensions),
        Schema::AllOf(schema) => Some(&mut schema.extensions),
        Schema::AnyOf(schema) => Some(&mut schema.extensions),
        _ => None,
    }
}

/// OpenAPI documentation for the Everruns API
#[derive(OpenApi)]
#[openapi(
    modifiers(&SdkMetadata),
    servers(
        (url = "https://app.everruns.com/api", description = "Production API"),
    ),
    paths(
        api::agents::create_agent,
        api::agents::list_agents,
        api::agents::get_agent,
        api::agents::get_agent_stats,
        api::agents::update_agent,
        api::agents::delete_agent,
        api::agents::export_agent,
        api::agents::import_agent,
        api::agents::agent_config,
        api::agents::check_agent_name,
        api::agent_credentials::list_credentials,
        api::agent_credentials::create_credential_binding,
        api::agent_credentials::set_credential_value,
        api::agent_credentials::delete_credential_binding,
        api::sessions::create_session,
        api::sessions::fork_session,
        api::sessions::list_sessions,
        api::sessions::get_session,
        api::sessions::get_session_resolved_model,
        api::sessions::list_session_participants,
        api::sessions::add_session_participant,
        api::sessions::leave_session_participant,
        api::sessions::get_session_context_report,
        api::sessions::get_session_stats,
        api::sessions::get_session_facets,
        api::sessions::update_session,
        api::sessions::delete_session,
        api::sessions::pin_session,
        api::sessions::unpin_session,
        api::sessions::archive_session,
        api::sessions::unarchive_session,
        api::sessions::cancel_turn,
        api::messages::create_message,
        api::messages::list_messages,
        api::messages::export_session_jsonl,
        api::voice::create_client_secret,
        api::voice::create_call,
        api::voice::attach_call,
        api::voice::end_call,
        api::voice::create_agent_voice_session,
        api::app_webhooks::invoke_webhook,
        api::app_a2a::invoke_a2a,
        api::app_a2a::agent_card,
        api::fcp::handshake,
        api::fcp::message,
        api::apps::list_app_runs,
        api::apps::add_a2a_channel,
        api::apps::regenerate_a2a_key,
        api::apps::add_api_endpoint_channel,
        api::apps::regenerate_api_endpoint_key,
        api::app_api::create_session,
        api::app_api::post_message,
        api::app_api::get_session,
        api::app_api::cancel_session,
        // Agent triggers (EVE-757)
        api::agent_triggers::list_agent_triggers,
        api::agent_triggers::create_agent_trigger,
        api::agent_triggers::get_agent_trigger,
        api::agent_triggers::list_agent_trigger_runs,
        api::agent_triggers::update_agent_trigger,
        api::agent_triggers::delete_agent_trigger,
        api::agent_triggers::trigger_agent_trigger,
        api::apps::create_app,
        api::apps::list_apps,
        api::apps::get_app,
        api::apps::update_app,
        api::apps::delete_app,
        api::apps::publish_app,
        api::apps::unpublish_app,
        api::apps::app_config,
        api::events::stream_sse,
        api::events::list_events,
        api::events::events_summary,
        api::providers::create_provider,
        api::providers::list_providers,
        api::providers::get_provider,
        api::providers::update_provider,
        api::providers::delete_provider,
        api::models::create_model,
        api::models::list_provider_models,
        api::models::list_all_models,
        api::models::get_model,
        api::models::update_model,
        api::models::delete_model,
        api::capabilities::list_capabilities,
        api::capabilities::get_capability,
        api::capabilities::declarative_capabilities_config,
        api::capabilities::create_declarative_capability,
        api::capabilities::list_declarative_capabilities,
        api::capabilities::get_declarative_capability,
        api::capabilities::update_declarative_capability,
        api::capabilities::delete_declarative_capability,
        api::capabilities::destroy_declarative_capability,
        api::capabilities::dry_run_guardrails,
        api::capabilities::list_guardrail_examples,
        api::users::list_users,
        // Session filesystem routes (under /v1/sessions/{session_id}/fs)
        // are intentionally omitted from the OpenAPI doc. They remain wired
        // for backward compatibility but are deprecated; the documented
        // surface is /v1/workspaces/{workspace_id}/fs. See knowledge/runtime-resources/workspace.md.
        // Session Git
        api::session_git::commit,
        api::session_git::log,
        api::session_git::diff,
        api::session_git::list_refs,
        api::session_git::create_branch,
        api::session_git::delete_branch,
        api::session_resources::list_resources,
        api::session_tasks::list_org_tasks,
        api::session_tasks::list_tasks,
        api::session_tasks::get_task,
        api::session_tasks::post_task_message,
        api::session_tasks::cancel_task,
        api::session_tasks::list_push_configs,
        api::session_tasks::create_push_config,
        api::session_tasks::delete_push_config,
        // Task webhooks
        api::task_webhooks::list_webhooks,
        api::task_webhooks::create_webhook,
        api::task_webhooks::get_webhook,
        api::task_webhooks::update_webhook,
        api::task_webhooks::delete_webhook,
        api::session_sandbox::get_sandbox,
        api::session_sandbox::manage_sandbox,
        api::mcp_servers::create_mcp_server,
        api::mcp_servers::list_mcp_servers,
        api::mcp_servers::get_mcp_server,
        api::mcp_servers::update_mcp_server,
        api::mcp_servers::delete_mcp_server,
        // Durable schedules
        api::durable::durable_config,
        api::durable::get_health,
        api::durable::get_metrics_timeseries,
        api::durable::cancel_workflow,
        api::durable::get_workflow,
        api::durable::get_workflow_events,
        api::durable::list_workflows,
        api::durable::stream_workflow_sse,
        api::durable::stream_durable_sse,
        api::durable::send_signal,
        api::durable::enqueue_task,
        api::durable::list_tasks,
        api::durable::list_workers,
        api::durable::drain_worker,
        api::durable::resume_worker,
        api::durable::list_dlq,
        api::durable::retry_dlq,
        api::durable::list_circuit_breakers,
        api::durable::get_circuit_breaker,
        api::durable::force_open_circuit_breaker,
        api::durable::force_close_circuit_breaker,
        api::durable::delete_circuit_breaker,
        api::schedules::create_schedule,
        api::schedules::list_schedules,
        api::schedules::get_schedule,
        api::schedules::update_schedule,
        api::schedules::delete_schedule,
        api::schedules::pause_schedule,
        api::schedules::resume_schedule,
        api::schedules::trigger_schedule,
        api::schedules::list_schedule_executions,
        api::schedules::get_execution,
        api::schedules::get_schedule_stats,
        // Harnesses
        api::harnesses::create_harness,
        api::harnesses::list_harnesses,
        api::harnesses::get_harness,
        api::harnesses::get_harness_stats,
        api::harnesses::update_harness,
        api::harnesses::delete_harness,
        api::harnesses::copy_harness,
        api::harnesses::preview_harness,
        api::harnesses::harness_config,
        api::harnesses::import_harness,
        api::harnesses::check_harness_name,
        // Harness examples
        api::harness_examples::list_examples,
        // Agents - additional
        api::agents::preview_agent,
        api::agents::analyze_agent,
        api::agents::trigger_health_check,
        api::agents::list_health_checks,
        api::agents::get_health_check,
        api::agents::get_latest_health_check,
        api::agents::upsert_agent,
        api::agents::copy_agent,
        api::agents::list_agent_versions,
        api::agents::create_agent_version,
        api::agents::set_default_agent_version,
        api::agents::rollback_agent_version,
        api::agents::fork_agent_version,
        api::agents::diff_agent_versions,
        // LLM Providers - additional
        api::providers::sync_models,
        api::providers::provider_config,
        api::models::model_config,
        api::mcp_servers::mcp_server_config,
        // Users - additional
        api::users::switch_org,
        api::users::update_profile,
        api::users::delete_account,
        api::users::export_user_data,
        // Resolver
        api::resolver::resolve_org,
        // Organizations
        api::organizations::create_organization,
        api::organizations::list_organizations,
        api::organizations::get_organization,
        api::organizations::update_organization,
        api::organizations::complete_org_onboarding,
        // Org feature flags
        api::org_feature_flags::get_org_feature_flags,
        api::org_feature_flags::get_org_feature_flag_settings,
        api::org_feature_flags::update_org_feature_flags,
        // Workspace (durable, named working area).
        //
        // NOTE: The legacy `/v1/sessions/{session_id}/fs/*` routes
        // (api::session_files::*) are intentionally NOT listed here. They
        // remain mounted for backwards compatibility but are delisted from
        // the published OpenAPI surface — clients should use
        // `/v1/workspaces/{workspace_id}/fs/*` (or the per-session alias
        // when one is needed for ergonomics).
        api::workspaces::list_workspaces,
        api::workspaces::create_workspace,
        api::workspaces::get_workspace,
        api::workspaces::update_workspace,
        api::workspaces::delete_workspace,
        // Workspace virtual filesystem
        api::workspace_files::get_root,
        api::workspace_files::get_path,
        api::workspace_files::create_path,
        api::workspace_files::update_path,
        api::workspace_files::delete_path,
        api::workspace_files::move_file,
        api::workspace_files::copy_file,
        api::workspace_files::stat_file,
        api::workspace_files::grep_files,
        api::workspace_files::download_path,
        api::workspace_files::preview_path,
        // Memory
        api::memory::create_memory,
        api::memory::list_memories,
        api::memory::get_memory,
        api::memory::update_memory,
        api::memory::sync_memory_now,
        api::memory::delete_memory,
        // Memory virtual filesystem
        api::memory_files::list_root,
        api::memory_files::get_file,
        api::memory_files::create_file,
        api::memory_files::update_file,
        api::memory_files::delete_file,
        api::memory_files::stat_action,
        api::memory_files::grep_action,
        api::memory_files::download_action,
        // Knowledge Bases
        api::knowledge_bases::create_kb,
        api::knowledge_bases::list_kbs,
        api::knowledge_bases::get_kb,
        api::knowledge_bases::update_kb,
        api::knowledge_bases::delete_kb,
        api::knowledge_bases::import_okf,
        api::knowledge_bases::export_okf,
        api::knowledge_bases::create_entry,
        api::knowledge_bases::list_entries,
        api::knowledge_bases::get_entry,
        api::knowledge_bases::update_entry,
        api::knowledge_bases::delete_entry,
        // Knowledge Indexes
        api::knowledge_indexes::create_index,
        api::knowledge_indexes::list_indexes,
        api::knowledge_indexes::get_index,
        api::knowledge_indexes::update_index,
        api::knowledge_indexes::delete_index,
        api::knowledge_indexes::sync_index,
        api::knowledge_indexes::list_documents,
        // Images
        api::images::upload_image,
        api::images::list_images,
        api::images::get_image,
        api::images::delete_image,
        api::images::get_thumbnail,
        // Session Databases
        api::session_databases::create_database,
        api::session_databases::list_databases,
        api::session_databases::get_database,
        api::session_databases::delete_database,
        api::session_databases::get_schema,
        // Session Storage
        api::session_storage::list_keys,
        api::session_storage::list_secrets,
        api::session_storage::batch_set_secrets,
        api::session_storage::delete_secret,
        // Client-side tool results
        api::tool_results::submit_tool_results,
        // Skills
        api::skills::create_skill,
        api::skills::upload_skill,
        api::skills::list_skills,
        api::skills::get_skill,
        api::skills::get_skill_content,
        api::skills::update_skill,
        api::skills::delete_skill,
        api::skills::validate_skill,
        api::skills::skill_config,
        api::skills::list_skills_usage,
        // Payments
        api::payments::create_payment_account,
        api::payments::list_payment_accounts,
        api::payments::get_payment_account,
        api::payments::update_payment_account,
        api::payments::disable_payment_account,
        api::payments::create_payment_policy,
        api::payments::list_payment_policies,
        api::payments::get_payment_policy,
        api::payments::update_payment_policy,
        api::payments::disable_payment_policy,
        api::payments::list_payment_attempts,
        // Reporting
        api::reporting::get_catalog,
        api::reporting::run_query,
        api::reporting::export_query,
        api::reporting::list_saved_reports,
        api::reporting::create_saved_report,
        api::reporting::get_saved_report,
        api::reporting::update_saved_report,
        api::reporting::delete_saved_report,
        api::reporting::run_saved_report,
        api::reporting::export_saved_report,
        api::reporting::get_diagnostics,
        api::reporting::backfill_reporting,
        api::reporting::run_projector,
        // Plugins & plugin marketplaces (EVE-667)
        api::plugins::list_plugins,
        api::plugins::get_plugin,
        api::plugins::install_plugin,
        api::plugins::uninstall_plugin,
        api::plugins::update_plugin,
        api::plugins::patch_installed_plugin,
        api::plugins::list_plugin_marketplaces,
        api::plugins::get_plugin_marketplace,
        api::plugins::create_plugin_marketplace,
        api::plugins::update_plugin_marketplace,
        api::plugins::delete_plugin_marketplace,
        api::plugins::sync_plugin_marketplace,
        api::plugins::get_marketplace_catalog,
    ),
    components(
        schemas(
            Agent, AgentStatus, everruns_platform::AgentVersion, everruns_platform::AgentVersionChangeKind,
            Session, SessionStatus, Event, EventContext, EventData,
            everruns_provider::typed_id::EventId,
            // Event data types
            InputMessageData, OutputMessageStartedData, OutputMessageDeltaData, OutputMessageCompletedData,
            ModelMetadata, TokenUsage,
            SessionContextReport, ContextReportSection, ContextReportContribution,
            TurnStartedData, TurnCompletedData, TurnFailedData, TurnSealedData,
            ReasonStartedData, ReasonCompletedData,
            ActStartedData, ActCompletedData, ToolCallSummary,
            ToolStartedData, ToolCompletedData,
            LlmGenerationData, LlmGenerationOutput, LlmGenerationMetadata,
            SessionStartedData, SessionModelChangedData,
            // Agent/Session types
            domains::agents::types::CreateAgentRequest, domains::agents::types::UpdateAgentRequest,
            domains::agents::types::CreateAgentVersionRequest,
            domains::agents::types::SetDefaultAgentVersionRequest,
            domains::agents::types::RollbackAgentVersionRequest,
            domains::agents::types::ForkAgentVersionRequest,
            domains::agents::types::AgentVersionDiffResponse,
            domains::agents::credentials::AgentCredentialBinding,
            domains::agents::credentials::CreateAgentCredentialBinding,
            api::agent_credentials::SetAgentCredentialValueRequest,
            ListResponse<domains::agents::credentials::AgentCredentialBinding>,
            api::sessions::CreateSessionRequest, api::sessions::UpdateSessionRequest,
            api::sessions::ForkSessionRequest,
            api::sessions::CancelTurnResponse, api::sessions::CancelStatus,
            api::sessions::SessionResolvedModelResponse,
            api::common::ResourceStatsResponse,
            api::messages::Message, api::messages::MessageRole, api::messages::ContentPart, api::messages::InputContentPart,
            api::messages::CreateMessageRequest, api::messages::InputMessage,
            api::messages::Controls, api::messages::ReasoningConfig,
            api::voice::VoiceSessionOptions, api::voice::VoiceClientSecretRequest,
            api::voice::VoiceCallRequest, api::voice::VoiceAttachRequest,
            api::voice::VoiceEndRequest, api::voice::VoiceClientSecretResponse,
            api::voice::VoiceCallResponse, api::voice::VoiceAttachResponse,
            api::voice::VoiceEndResponse,
            api::voice::VoiceSessionResponse<api::voice::VoiceCallResponse>,
            api::app_webhooks::WebhookInvocationResponse,
            api::apps::ListAppRunsQuery,
            api::apps::AddA2aChannelHttpRequest,
            api::apps::AddApiEndpointChannelHttpRequest,
            domains::apps::types::AppRunEvent,
            domains::apps::types::AppRunBucket,
            domains::apps::types::AppRunListResponse,
            domains::apps::AddA2aChannelOutput,
            domains::apps::RegenerateA2aApiKeyOutput,
            domains::apps::AddApiEndpointChannelOutput,
            domains::apps::RegenerateApiEndpointApiKeyOutput,
            // Agent triggers (EVE-757)
            everruns_platform::AgentTrigger,
            everruns_platform::AgentTriggerType,
            everruns_platform::ScheduleTriggerConfig,
            everruns_platform::InvocationSessionMode,
            domains::agent_triggers::types::CreateAgentTriggerRequest,
            domains::agent_triggers::types::UpdateAgentTriggerRequest,
            domains::agent_triggers::types::AgentTriggerRun,
            domains::agent_triggers::TriggerAgentTriggerOutput,
            api::app_api::MessageBody,
            api::app_api::SessionRef,
            api::app_api::SessionStatus,
            api::app_api::AgentMessage,
            ListResponse<Agent>,
            PaginatedResponse<Session>,
            ListResponse<api::messages::Message>,
            ListResponse<Event>,
            domains::events::EventsSummaryResult, domains::events::EventTypeCountOut,
            Provider, ProviderTraceConfig, ProviderRequestOptions, ProviderRequestHeader, DriverId, ProviderStatus,
            Model, ModelWithProvider,
            api::providers::CreateProviderRequest,
            api::providers::UpdateProviderRequest,
            api::providers::ProvidersConfigResponse,
            api::providers::DriverCredentialInfo,
            everruns_provider::credential_schema::CredentialFormSchema,
            everruns_provider::credential_schema::FormField,
            everruns_provider::credential_schema::FieldType,
            api::models::CreateModelRequest,
            api::models::UpdateModelRequest,
            CapabilityInfo,
            ListResponse<CapabilityInfo>,
            domains::capabilities::types::GuardrailsDryRunRequest,
            domains::capabilities::types::GuardrailsDryRunHit,
            domains::capabilities::types::GuardrailsDryRunResponse,
            domains::capabilities::types::GuardrailExample,
            domains::capabilities::types::GuardrailExamplesResponse,
            everruns_core::GuardrailStage,
            everruns_core::GuardrailAction,
            // Harness types
            everruns_platform::Harness, everruns_platform::HarnessStatus, everruns_core::ResourceConfigResponse,
            domains::harnesses::types::CreateHarnessRequest,
            domains::harnesses::types::UpdateHarnessRequest,
            domains::harnesses::types::PreviewHarnessRequest,
            domains::harnesses::types::HarnessPreviewResponse,
            api::harness_examples::HarnessExample,
            ListResponse<everruns_platform::Harness>,
            api::users::User,
            api::users::ListUsersQuery,
            ListResponse<api::users::User>,
            SessionFile, FileInfo, FileStat, GrepMatch, GrepResult,
            LeasedResource,
            // Session filesystem DTOs intentionally omitted — see paths(...) above.
            ListResponse<FileInfo>,
            ListResponse<GrepResult>,
            api::session_sandbox::SessionSandboxAction,
            api::session_sandbox::SessionSandboxStatusValue,
            api::session_sandbox::GetSessionSandboxResponse,
            api::session_sandbox::ManageSessionSandboxRequest,
            api::session_sandbox::ManageSessionSandboxResponse,
            // Session Git types
            api::session_git::CommitRequest, api::session_git::LogQuery,
            api::session_git::DiffQuery, api::session_git::CreateBranchRequest,
            api::session_git::SuccessResponse,
            domains::session_git::CommitResult, domains::session_git::GitCommitInfo,
            domains::session_git::GitDiff, domains::session_git::GitDiffEntry,
            domains::session_git::GitDiffStats, domains::session_git::GitRefInfo,
            // Tool types
            ToolCall,
            everruns_provider::tool_types::ToolDefinition, everruns_provider::tool_types::BuiltinTool, everruns_provider::tool_types::ClientSideTool,
            everruns_provider::tool_types::ToolPolicy, everruns_provider::tool_types::ToolHints,
            everruns_core::events::ToolCallRequestedData,
            api::tool_results::SubmitToolResultsRequest,
            api::tool_results::ClientToolResult,
            api::tool_results::SubmitToolResultsResponse,
            // MCP Server types
            McpServer, McpServerStatus, McpServerTransportType,
            everruns_core::mcp_server::McpToolAnnotations,
            everruns_core::mcp_server::McpExecuteError,
            everruns_core::mcp_server::McpErrorCode,
            everruns_core::mcp_server::McpErrorCategory,
            domains::mcp_servers::types::CreateMcpServerRequest,
            domains::mcp_servers::types::UpdateMcpServerRequest,
            ListResponse<McpServer>,
            // Schedule types
            api::schedules::ScheduleTarget,
            api::schedules::CreateScheduleRequest,
            api::schedules::UpdateScheduleRequest,
            api::schedules::ScheduleResponse,
            api::schedules::ScheduleTargetResponse,
            api::schedules::SchedulesListResponse,
            api::schedules::ScheduleExecutionResponse,
            api::schedules::ScheduleExecutionsListResponse,
            api::schedules::ScheduleStatsResponse,
            api::schedules::TriggerResponse,
            api::schedules::ListSchedulesQuery,
            api::schedules::ListExecutionsQuery,
            // Skill types
            Skill, SkillSourceType, SkillStatus, SkillContent, SkillFileEntry,
            SkillValidationResult,
            domains::skills::types::CreateSkillRequest,
            domains::skills::types::UpdateSkillRequest,
            api::skills::ValidateSkillRequest,
            ListResponse<Skill>,
            api::memory::CreateMemoryRequest,
            api::memory::UpdateMemoryRequest,
            api::memory::ListMemoriesQuery,
            api::memory::MemoryResponse,
            api::workspaces::WorkspaceResponse,
            api::workspaces::CreateWorkspaceRequest,
            api::workspaces::UpdateWorkspaceRequest,
            api::workspaces::ListWorkspacesQuery,
            // Workspace virtual filesystem (reuses session_files request/response types).
            api::session_files::CreateFileRequest,
            api::session_files::UpdateFileRequest,
            api::session_files::MoveFileRequest,
            api::session_files::CopyFileRequest,
            api::session_files::GrepRequest,
            api::session_files::StatRequest,
            api::session_files::GetQuery,
            api::session_files::DeleteQuery,
            api::session_files::DeleteResponse,
            api::session_files::GetResponse,
            api::memory_files::CreateMemoryFileRequest,
            api::memory_files::UpdateMemoryFileRequest,
            api::memory_files::GrepRequest,
            api::memory_files::GrepResultEntry,
            api::memory_files::StatRequest,
            api::memory_files::DeleteQuery,
            api::memory_files::MemoryFile,
            api::memory_files::MemoryFileInfo,
            everruns_platform::Budget,
            everruns_core::budget::BudgetStatus,
            everruns_core::budget::BudgetSubjectType,
            everruns_core::budget::BudgetPeriod,
            everruns_platform::LedgerEntry,
            everruns_core::budget::BudgetCheckResult,
            api::budgets::CreateBudgetRequest,
            api::budgets::UpdateBudgetRequest,
            api::budgets::TopUpRequest,
            domains::budgets::ResumeSessionBudgetsResult,
            api::user_connections::ConnectionResponse,
            api::user_connections::ApiKeyConnectionRequest,
            api::knowledge_bases::CreateKnowledgeBaseRequest,
            api::knowledge_bases::UpdateKnowledgeBaseRequest,
            api::knowledge_bases::ListKnowledgeBasesQuery,
            api::knowledge_bases::KnowledgeBaseResponse,
            api::knowledge_bases::CreateKnowledgeEntryRequest,
            api::knowledge_bases::UpdateKnowledgeEntryRequest,
            api::knowledge_bases::ListKnowledgeEntriesQuery,
            api::knowledge_bases::KnowledgeEntryResponse,
            api::knowledge_bases::ImportOkfBundleRequest,
            api::knowledge_bases::OkfFileInput,
            api::knowledge_bases::OkfImportSummary,
            api::knowledge_indexes::CreateKnowledgeIndexRequest,
            api::knowledge_indexes::UpdateKnowledgeIndexRequest,
            api::knowledge_indexes::ListKnowledgeIndexesQuery,
            api::knowledge_indexes::KnowledgeIndexResponse,
            api::knowledge_indexes::KnowledgeIndexDocumentResponse,
            everruns_platform::payment::PaymentAccount,
            everruns_platform::payment::PaymentAttempt,
            everruns_platform::payment::PaymentPolicy,
            everruns_core::payment::PaymentRail,
            everruns_platform::payment::PaymentStatus,
            everruns_platform::payment::PaymentOwnerType,
            domains::payments::types::CreatePaymentAccountRequest,
            domains::payments::types::UpdatePaymentAccountRequest,
            domains::payments::types::CreatePaymentPolicyRequest,
            domains::payments::types::UpdatePaymentPolicyRequest,
            everruns_platform::reporting::DatasetCatalog,
            everruns_platform::reporting::DatasetCatalogEntry,
            everruns_platform::reporting::ReportColumn,
            everruns_platform::reporting::ReportColumnKind,
            everruns_platform::reporting::ReportFilter,
            everruns_platform::reporting::ReportFilterOp,
            everruns_platform::reporting::ReportOrderBy,
            everruns_platform::reporting::ReportOrderDirection,
            everruns_platform::reporting::ReportQuery,
            everruns_platform::reporting::ReportResult,
            everruns_platform::reporting::ReportTimeRange,
            ListResponse<domains::reporting::types::SavedReport>,
            domains::reporting::types::CreateSavedReportRequest,
            domains::reporting::types::DatasetProjectorLag,
            domains::reporting::types::ExportReportQueryRequest,
            domains::reporting::types::ExportSavedReportRequest,
            domains::reporting::types::FailedReportingOutboxRow,
            domains::reporting::types::ReportExport,
            domains::reporting::types::ReportExportFormat,
            domains::reporting::types::ReportingBackfillRequest,
            domains::reporting::types::ReportingBackfillResult,
            domains::reporting::types::ReportingDiagnostics,
            domains::reporting::types::ReportingOutboxDiagnostics,
            domains::reporting::types::SavedReport,
            domains::reporting::types::SavedReportDashboardMetadata,
            domains::reporting::types::UpdateSavedReportRequest,
            api::reporting::ProjectorRunQuery,
            domains::reporting::types::ProjectorRunResult,
            api::task_webhooks::TaskWebhookResponse,
            api::task_webhooks::CreateTaskWebhookRequest,
            api::task_webhooks::UpdateTaskWebhookRequest,
            api::session_tasks::CreatePushConfigBody,
            domains::session_tasks::TaskPushConfig,
        )
    ),
    tags(
        (name = "agents", description = "Agent management endpoints"),
        (name = "sessions", description = "Session management endpoints"),
        (name = "messages", description = "Message management endpoints"),
        (name = "voice", description = "Realtime voice session endpoints"),
        (name = "events", description = "Event streaming endpoints (SSE)"),
        (name = "providers", description = "LLM Provider management endpoints"),
        (name = "models", description = "LLM Model management endpoints"),
        (name = "capabilities", description = "Capability management endpoints"),
        (name = "users", description = "User management endpoints"),
        (name = "filesystem", description = "Session virtual filesystem endpoints"),
        (name = "session-resources", description = "Session leased-resource visibility endpoints"),
        (name = "session-sandbox", description = "Managed session sandbox lifecycle endpoints"),
        (name = "mcp-servers", description = "MCP Server management endpoints"),
        (name = "durable-schedules", description = "Durable scheduled tasks management endpoints"),
        (name = "organizations", description = "Organization management endpoints"),
        (name = "memory", description = "Org-scoped named Memory management endpoints"),
        (name = "knowledge_bases", description = "Knowledge base and entry management endpoints"),
        (name = "knowledge_indexes", description = "Knowledge index and document management endpoints"),
        (name = "images", description = "Image upload and management endpoints"),
        (name = "session-databases", description = "Session-scoped SQL database endpoints"),
        (name = "session-storage", description = "Session key-value storage endpoints"),
        (name = "harnesses", description = "Harness management endpoints"),
        (name = "agent-triggers", description = "Agent-owned schedule trigger endpoints"),
        (name = "skills", description = "Skills registry endpoints"),
        (name = "payments", description = "Machine payment wallet, policy, and attempt endpoints"),
        (name = "reporting", description = "Org-scoped semantic reporting endpoints"),
        (name = "task-webhooks", description = "Outbound HTTP webhooks fired on terminal task transitions"),
    ),
    info(
        title = "Everruns API",
        version = "0.2.0",
        description = "API for managing AI agents, sessions, messages, and events",
        license(name = "MIT", url = "https://opensource.org/licenses/MIT")
    )
)]
pub struct ApiDoc;

impl ApiDoc {
    /// Generate the OpenAPI spec as a pretty-printed JSON string
    pub fn to_json() -> String {
        Self::openapi()
            .to_pretty_json()
            .expect("Failed to serialize OpenAPI spec")
    }
}
