// OpenAPI specification generation
//
// This module defines the OpenAPI spec for the Everruns API.
// It can be used by both the main API server (for Swagger UI)
// and the export-openapi binary (for static spec generation).

use crate::api;
use crate::api::{ListResponse, PaginatedResponse};
use crate::domains;
use everruns_core::llm_models::LlmProvider;
use everruns_core::{
    Agent, AgentStatus, CapabilityInfo, ContextReportContribution, ContextReportSection, Event,
    EventContext, EventData, FileInfo, FileStat, GrepMatch, GrepResult, LeasedResource, LlmModel,
    LlmModelWithProvider, LlmProviderStatus, LlmProviderType, McpServer, McpServerStatus,
    McpServerTransportType, Session, SessionContextReport, SessionFile, SessionStatus, Skill,
    SkillContent, SkillFileEntry, SkillSourceType, SkillStatus, SkillValidationResult, ToolCall,
    events::{
        ActCompletedData, ActStartedData, InputMessageData, LlmGenerationData,
        LlmGenerationMetadata, LlmGenerationOutput, ModelMetadata, OutputMessageCompletedData,
        OutputMessageDeltaData, OutputMessageStartedData, ReasonCompletedData, ReasonStartedData,
        SessionStartedData, TokenUsage, ToolCallSummary, ToolCompletedData, ToolStartedData,
        TurnCompletedData, TurnFailedData, TurnStartedData,
    },
};
use utoipa::OpenApi;

/// OpenAPI documentation for the Everruns API
#[derive(OpenApi)]
#[openapi(
    servers(
        (url = "https://app.everruns.com/api", description = "Production API"),
    ),
    paths(
        api::agents::create_agent,
        api::agents::list_agents,
        api::agents::get_agent,
        api::agents::get_agent_stats,
        api::agents::update_agent,
        api::agents::delete_agent,
        api::agents::export_agent,
        api::agents::import_agent,
        api::agents::agent_config,
        api::agents::check_agent_name,
        api::sessions::create_session,
        api::sessions::list_sessions,
        api::sessions::get_session,
        api::sessions::get_session_context_report,
        api::sessions::get_session_stats,
        api::sessions::update_session,
        api::sessions::delete_session,
        api::sessions::get_or_create_chat_session,
        api::sessions::pin_session,
        api::sessions::unpin_session,
        api::sessions::cancel_turn,
        api::messages::create_message,
        api::messages::list_messages,
        api::messages::export_session_jsonl,
        api::voice::create_client_secret,
        api::voice::create_call,
        api::voice::attach_call,
        api::voice::end_call,
        api::voice::create_agent_voice_session,
        api::voice::create_chat_voice_session,
        api::app_webhooks::invoke_webhook,
        api::app_a2a::invoke_a2a,
        api::app_a2a::agent_card,
        api::fcp::handshake,
        api::fcp::message,
        api::apps::list_app_runs,
        api::apps::add_a2a_channel,
        api::apps::regenerate_a2a_key,
        api::apps::create_app,
        api::apps::list_apps,
        api::apps::get_app,
        api::apps::update_app,
        api::apps::delete_app,
        api::apps::publish_app,
        api::apps::unpublish_app,
        api::apps::app_config,
        api::events::stream_sse,
        api::events::list_events,
        api::events::events_summary,
        api::llm_providers::create_provider,
        api::llm_providers::list_providers,
        api::llm_providers::get_provider,
        api::llm_providers::update_provider,
        api::llm_providers::delete_provider,
        api::llm_models::create_model,
        api::llm_models::list_provider_models,
        api::llm_models::list_all_models,
        api::llm_models::get_model,
        api::llm_models::update_model,
        api::llm_models::delete_model,
        api::capabilities::list_capabilities,
        api::capabilities::get_capability,
        api::capabilities::declarative_capabilities_config,
        api::capabilities::create_declarative_capability,
        api::capabilities::list_declarative_capabilities,
        api::capabilities::get_declarative_capability,
        api::capabilities::update_declarative_capability,
        api::capabilities::delete_declarative_capability,
        api::capabilities::destroy_declarative_capability,
        api::users::list_users,
        api::session_files::get_root,
        api::session_files::get_path,
        api::session_files::download_path,
        api::session_files::create_path,
        api::session_files::update_path,
        api::session_files::delete_path,
        api::session_files::move_file,
        api::session_files::copy_file,
        api::session_files::grep_files,
        api::session_files::stat_file,
        // Session Git
        api::session_git::commit,
        api::session_git::log,
        api::session_git::diff,
        api::session_git::list_refs,
        api::session_git::create_branch,
        api::session_git::delete_branch,
        api::session_resources::list_resources,
        api::session_tasks::list_tasks,
        api::session_tasks::get_task,
        api::session_tasks::post_task_message,
        api::session_tasks::cancel_task,
        api::session_sandbox::get_sandbox,
        api::session_sandbox::manage_sandbox,
        api::mcp_servers::create_mcp_server,
        api::mcp_servers::list_mcp_servers,
        api::mcp_servers::get_mcp_server,
        api::mcp_servers::update_mcp_server,
        api::mcp_servers::delete_mcp_server,
        // Durable schedules
        api::durable::durable_config,
        api::durable::get_health,
        api::durable::get_metrics_timeseries,
        api::durable::cancel_workflow,
        api::durable::get_workflow,
        api::durable::get_workflow_events,
        api::durable::list_workflows,
        api::durable::stream_workflow_sse,
        api::durable::stream_durable_sse,
        api::durable::send_signal,
        api::durable::enqueue_task,
        api::durable::list_tasks,
        api::durable::list_workers,
        api::durable::drain_worker,
        api::durable::resume_worker,
        api::durable::list_dlq,
        api::durable::retry_dlq,
        api::durable::list_circuit_breakers,
        api::durable::get_circuit_breaker,
        api::durable::force_open_circuit_breaker,
        api::durable::force_close_circuit_breaker,
        api::durable::delete_circuit_breaker,
        api::schedules::create_schedule,
        api::schedules::list_schedules,
        api::schedules::get_schedule,
        api::schedules::update_schedule,
        api::schedules::delete_schedule,
        api::schedules::pause_schedule,
        api::schedules::resume_schedule,
        api::schedules::trigger_schedule,
        api::schedules::list_schedule_executions,
        api::schedules::get_execution,
        api::schedules::get_schedule_stats,
        // Harnesses
        api::harnesses::create_harness,
        api::harnesses::list_harnesses,
        api::harnesses::get_harness,
        api::harnesses::get_harness_stats,
        api::harnesses::update_harness,
        api::harnesses::delete_harness,
        api::harnesses::copy_harness,
        api::harnesses::preview_harness,
        api::harnesses::harness_config,
        api::harnesses::import_harness,
        api::harnesses::check_harness_name,
        // Harness examples
        api::harness_examples::list_examples,
        // Agents - additional
        api::agents::preview_agent,
        api::agents::upsert_agent,
        api::agents::copy_agent,
        api::agents::list_agent_versions,
        api::agents::create_agent_version,
        api::agents::set_default_agent_version,
        api::agents::rollback_agent_version,
        api::agents::fork_agent_version,
        api::agents::diff_agent_versions,
        // LLM Providers - additional
        api::llm_providers::sync_models,
        api::llm_providers::llm_provider_config,
        api::llm_models::llm_model_config,
        api::mcp_servers::mcp_server_config,
        // Users - additional
        api::users::switch_org,
        api::users::update_profile,
        api::users::delete_account,
        api::users::export_user_data,
        // Resolver
        api::resolver::resolve_org,
        // Organizations
        api::organizations::create_organization,
        api::organizations::list_organizations,
        api::organizations::get_organization,
        api::organizations::update_organization,
        // Org feature flags
        api::org_feature_flags::get_org_feature_flags,
        api::org_feature_flags::get_org_feature_flag_settings,
        api::org_feature_flags::update_org_feature_flags,
        // Memory
        api::memory::create_memory,
        api::memory::list_memories,
        api::memory::get_memory,
        api::memory::update_memory,
        api::memory::sync_memory_now,
        api::memory::delete_memory,
        // Knowledge Bases
        api::knowledge_bases::create_kb,
        api::knowledge_bases::list_kbs,
        api::knowledge_bases::get_kb,
        api::knowledge_bases::update_kb,
        api::knowledge_bases::delete_kb,
        api::knowledge_bases::create_entry,
        api::knowledge_bases::list_entries,
        api::knowledge_bases::get_entry,
        api::knowledge_bases::update_entry,
        api::knowledge_bases::delete_entry,
        // Images
        api::images::upload_image,
        api::images::list_images,
        api::images::get_image,
        api::images::delete_image,
        api::images::get_thumbnail,
        // Session Databases
        api::session_databases::create_database,
        api::session_databases::list_databases,
        api::session_databases::get_database,
        api::session_databases::delete_database,
        api::session_databases::get_schema,
        // Session Storage
        api::session_storage::list_keys,
        api::session_storage::list_secrets,
        api::session_storage::batch_set_secrets,
        // Client-side tool results
        api::tool_results::submit_tool_results,
        // Skills
        api::skills::create_skill,
        api::skills::upload_skill,
        api::skills::list_skills,
        api::skills::get_skill,
        api::skills::get_skill_content,
        api::skills::update_skill,
        api::skills::delete_skill,
        api::skills::validate_skill,
        api::skills::skill_config,
        api::skills::list_skills_usage,
        // Payments
        api::payments::create_payment_account,
        api::payments::list_payment_accounts,
        api::payments::get_payment_account,
        api::payments::update_payment_account,
        api::payments::disable_payment_account,
        api::payments::create_payment_policy,
        api::payments::list_payment_policies,
        api::payments::get_payment_policy,
        api::payments::update_payment_policy,
        api::payments::disable_payment_policy,
        api::payments::list_payment_attempts,
        // Reporting
        api::reporting::get_catalog,
        api::reporting::run_query,
        api::reporting::export_query,
        api::reporting::list_saved_reports,
        api::reporting::create_saved_report,
        api::reporting::get_saved_report,
        api::reporting::update_saved_report,
        api::reporting::delete_saved_report,
        api::reporting::run_saved_report,
        api::reporting::export_saved_report,
        api::reporting::get_diagnostics,
        api::reporting::backfill_reporting,
        api::reporting::run_projector,
    ),
    components(
        schemas(
            Agent, AgentStatus, everruns_core::AgentVersion, everruns_core::AgentVersionChangeKind,
            Session, SessionStatus, Event, EventContext, EventData,
            everruns_core::typed_id::EventId,
            // Event data types
            InputMessageData, OutputMessageStartedData, OutputMessageDeltaData, OutputMessageCompletedData,
            ModelMetadata, TokenUsage,
            SessionContextReport, ContextReportSection, ContextReportContribution,
            TurnStartedData, TurnCompletedData, TurnFailedData,
            ReasonStartedData, ReasonCompletedData,
            ActStartedData, ActCompletedData, ToolCallSummary,
            ToolStartedData, ToolCompletedData,
            LlmGenerationData, LlmGenerationOutput, LlmGenerationMetadata,
            SessionStartedData,
            // Agent/Session types
            domains::agents::types::CreateAgentRequest, domains::agents::types::UpdateAgentRequest,
            domains::agents::types::CreateAgentVersionRequest,
            domains::agents::types::SetDefaultAgentVersionRequest,
            domains::agents::types::RollbackAgentVersionRequest,
            domains::agents::types::ForkAgentVersionRequest,
            domains::agents::types::AgentVersionDiffResponse,
            api::sessions::CreateSessionRequest, api::sessions::UpdateSessionRequest,
            api::sessions::CancelTurnResponse, api::sessions::CancelStatus,
            api::common::ResourceStatsResponse,
            api::messages::Message, api::messages::MessageRole, api::messages::ContentPart, api::messages::InputContentPart,
            api::messages::CreateMessageRequest, api::messages::InputMessage,
            api::messages::Controls, api::messages::ReasoningConfig,
            api::voice::VoiceSessionOptions, api::voice::VoiceClientSecretRequest,
            api::voice::VoiceCallRequest, api::voice::VoiceAttachRequest,
            api::voice::VoiceEndRequest, api::voice::VoiceClientSecretResponse,
            api::voice::VoiceCallResponse, api::voice::VoiceAttachResponse,
            api::voice::VoiceEndResponse,
            api::voice::VoiceSessionResponse<api::voice::VoiceCallResponse>,
            api::app_webhooks::WebhookInvocationResponse,
            api::apps::ListAppRunsQuery,
            api::apps::AddA2aChannelHttpRequest,
            domains::apps::types::AppRunEvent,
            domains::apps::types::AppRunBucket,
            domains::apps::types::AppRunListResponse,
            domains::apps::AddA2aChannelOutput,
            domains::apps::RegenerateA2aApiKeyOutput,
            ListResponse<Agent>,
            PaginatedResponse<Session>,
            ListResponse<api::messages::Message>,
            ListResponse<Event>,
            domains::events::EventsSummaryResult, domains::events::EventTypeCountOut,
            LlmProvider, LlmProviderType, LlmProviderStatus,
            LlmModel, LlmModelWithProvider,
            api::llm_providers::CreateLlmProviderRequest,
            api::llm_providers::UpdateLlmProviderRequest,
            api::llm_models::CreateLlmModelRequest,
            api::llm_models::UpdateLlmModelRequest,
            CapabilityInfo,
            ListResponse<CapabilityInfo>,
            // Harness types
            everruns_core::Harness, everruns_core::HarnessStatus, everruns_core::ResourceConfigResponse,
            domains::harnesses::types::CreateHarnessRequest,
            domains::harnesses::types::UpdateHarnessRequest,
            domains::harnesses::types::PreviewHarnessRequest,
            domains::harnesses::types::HarnessPreviewResponse,
            api::harness_examples::HarnessExample,
            ListResponse<everruns_core::Harness>,
            api::users::User,
            api::users::ListUsersQuery,
            ListResponse<api::users::User>,
            SessionFile, FileInfo, FileStat, GrepMatch, GrepResult,
            LeasedResource,
            api::session_files::CreateFileRequest, api::session_files::UpdateFileRequest,
            api::session_files::MoveFileRequest, api::session_files::CopyFileRequest,
            api::session_files::GrepRequest, api::session_files::DeleteResponse,
            api::session_files::GetQuery, api::session_files::DeleteQuery, api::session_files::GetResponse,
            ListResponse<FileInfo>,
            ListResponse<GrepResult>,
            api::session_sandbox::SessionSandboxAction,
            api::session_sandbox::SessionSandboxStatusValue,
            api::session_sandbox::GetSessionSandboxResponse,
            api::session_sandbox::ManageSessionSandboxRequest,
            api::session_sandbox::ManageSessionSandboxResponse,
            // Session Git types
            api::session_git::CommitRequest, api::session_git::LogQuery,
            api::session_git::DiffQuery, api::session_git::CreateBranchRequest,
            api::session_git::SuccessResponse,
            domains::session_git::CommitResult, domains::session_git::GitCommitInfo,
            domains::session_git::GitDiff, domains::session_git::GitDiffEntry,
            domains::session_git::GitDiffStats, domains::session_git::GitRefInfo,
            // Tool types
            ToolCall,
            everruns_core::ToolDefinition, everruns_core::BuiltinTool, everruns_core::ClientSideTool,
            everruns_core::ToolPolicy, everruns_core::ToolHints,
            everruns_core::ToolCallRequestedData,
            api::tool_results::SubmitToolResultsRequest,
            api::tool_results::ClientToolResult,
            api::tool_results::SubmitToolResultsResponse,
            // MCP Server types
            McpServer, McpServerStatus, McpServerTransportType,
            everruns_core::mcp_server::McpToolAnnotations,
            everruns_core::mcp_server::McpExecuteError,
            everruns_core::mcp_server::McpErrorCode,
            everruns_core::mcp_server::McpErrorCategory,
            domains::mcp_servers::types::CreateMcpServerRequest,
            domains::mcp_servers::types::UpdateMcpServerRequest,
            ListResponse<McpServer>,
            // Schedule types
            api::schedules::ScheduleTarget,
            api::schedules::CreateScheduleRequest,
            api::schedules::UpdateScheduleRequest,
            api::schedules::ScheduleResponse,
            api::schedules::ScheduleTargetResponse,
            api::schedules::SchedulesListResponse,
            api::schedules::ScheduleExecutionResponse,
            api::schedules::ScheduleExecutionsListResponse,
            api::schedules::ScheduleStatsResponse,
            api::schedules::TriggerResponse,
            api::schedules::ListSchedulesQuery,
            api::schedules::ListExecutionsQuery,
            // Skill types
            Skill, SkillSourceType, SkillStatus, SkillContent, SkillFileEntry,
            SkillValidationResult,
            domains::skills::types::CreateSkillRequest,
            domains::skills::types::UpdateSkillRequest,
            api::skills::ValidateSkillRequest,
            ListResponse<Skill>,
            api::memory::CreateMemoryRequest,
            api::memory::UpdateMemoryRequest,
            api::memory::ListMemoriesQuery,
            api::memory::MemoryResponse,
            api::knowledge_bases::CreateKnowledgeBaseRequest,
            api::knowledge_bases::UpdateKnowledgeBaseRequest,
            api::knowledge_bases::ListKnowledgeBasesQuery,
            api::knowledge_bases::KnowledgeBaseResponse,
            api::knowledge_bases::CreateKnowledgeEntryRequest,
            api::knowledge_bases::UpdateKnowledgeEntryRequest,
            api::knowledge_bases::ListKnowledgeEntriesQuery,
            api::knowledge_bases::KnowledgeEntryResponse,
            everruns_core::payment::PaymentAccount,
            everruns_core::payment::PaymentAttempt,
            everruns_core::payment::PaymentPolicy,
            everruns_core::payment::PaymentRail,
            everruns_core::payment::PaymentStatus,
            everruns_core::payment::PaymentOwnerType,
            domains::payments::types::CreatePaymentAccountRequest,
            domains::payments::types::UpdatePaymentAccountRequest,
            domains::payments::types::CreatePaymentPolicyRequest,
            domains::payments::types::UpdatePaymentPolicyRequest,
            everruns_core::reporting::DatasetCatalog,
            everruns_core::reporting::DatasetCatalogEntry,
            everruns_core::reporting::ReportColumn,
            everruns_core::reporting::ReportColumnKind,
            everruns_core::reporting::ReportFilter,
            everruns_core::reporting::ReportFilterOp,
            everruns_core::reporting::ReportOrderBy,
            everruns_core::reporting::ReportOrderDirection,
            everruns_core::reporting::ReportQuery,
            everruns_core::reporting::ReportResult,
            everruns_core::reporting::ReportTimeRange,
            ListResponse<domains::reporting::types::SavedReport>,
            domains::reporting::types::CreateSavedReportRequest,
            domains::reporting::types::DatasetProjectorLag,
            domains::reporting::types::ExportReportQueryRequest,
            domains::reporting::types::ExportSavedReportRequest,
            domains::reporting::types::FailedReportingOutboxRow,
            domains::reporting::types::ReportExport,
            domains::reporting::types::ReportExportFormat,
            domains::reporting::types::ReportingBackfillRequest,
            domains::reporting::types::ReportingBackfillResult,
            domains::reporting::types::ReportingDiagnostics,
            domains::reporting::types::ReportingOutboxDiagnostics,
            domains::reporting::types::SavedReport,
            domains::reporting::types::SavedReportDashboardMetadata,
            domains::reporting::types::UpdateSavedReportRequest,
            api::reporting::ProjectorRunQuery,
            domains::reporting::types::ProjectorRunResult,
        )
    ),
    tags(
        (name = "agents", description = "Agent management endpoints"),
        (name = "sessions", description = "Session management endpoints"),
        (name = "messages", description = "Message management endpoints"),
        (name = "voice", description = "Realtime voice session endpoints"),
        (name = "events", description = "Event streaming endpoints (SSE)"),
        (name = "llm-providers", description = "LLM Provider management endpoints"),
        (name = "llm-models", description = "LLM Model management endpoints"),
        (name = "capabilities", description = "Capability management endpoints"),
        (name = "users", description = "User management endpoints"),
        (name = "filesystem", description = "Session virtual filesystem endpoints"),
        (name = "session-resources", description = "Session leased-resource visibility endpoints"),
        (name = "session-sandbox", description = "Managed session sandbox lifecycle endpoints"),
        (name = "mcp-servers", description = "MCP Server management endpoints"),
        (name = "durable-schedules", description = "Durable scheduled tasks management endpoints"),
        (name = "organizations", description = "Organization management endpoints"),
        (name = "memory", description = "Org-scoped named Memory management endpoints"),
        (name = "knowledge_bases", description = "Knowledge base and entry management endpoints"),
        (name = "images", description = "Image upload and management endpoints"),
        (name = "session-databases", description = "Session-scoped SQL database endpoints"),
        (name = "session-storage", description = "Session key-value storage endpoints"),
        (name = "harnesses", description = "Harness management endpoints"),
        (name = "skills", description = "Skills registry endpoints"),
        (name = "payments", description = "Machine payment wallet, policy, and attempt endpoints"),
        (name = "reporting", description = "Org-scoped semantic reporting endpoints"),
    ),
    info(
        title = "Everruns API",
        version = "0.2.0",
        description = "API for managing AI agents, sessions, messages, and events",
        license(name = "MIT", url = "https://opensource.org/licenses/MIT")
    )
)]
pub struct ApiDoc;

impl ApiDoc {
    /// Generate the OpenAPI spec as a pretty-printed JSON string
    pub fn to_json() -> String {
        Self::openapi()
            .to_pretty_json()
            .expect("Failed to serialize OpenAPI spec")
    }
}
