// Password hashing using Argon2id
// Decision: Use Argon2id as it's the recommended algorithm for password hashing
// Decision: Pin the cost parameters explicitly (EVE-630) rather than relying on
// `Argon2::default()`, so an `argon2` dependency bump cannot silently change the
// work factor.

use anyhow::Result;
use argon2::{
    Algorithm, Argon2, Params, Version,
    password_hash::{PasswordHasher, PasswordVerifier, phc::PasswordHash},
};

// Pinned Argon2id cost parameters (EVE-630). These match an OWASP-recommended
// baseline configuration (and the current `argon2` v0.5 defaults): 19 MiB of
// memory, 2 iterations, 1 lane. Pinning them here keeps the work factor stable
// and auditable across dependency upgrades instead of inheriting whatever
// `Argon2::default()` happens to be. Raising the cost later is safe: each stored
// hash is PHC-encoded with the params used to create it, so `verify_password`
// always verifies with the embedded params and existing hashes keep working.
const ARGON2_MEMORY_KIB: u32 = 19_456;
const ARGON2_ITERATIONS: u32 = 2;
const ARGON2_PARALLELISM: u32 = 1;

/// The pinned Argon2id hasher used for both hashing and verification.
fn argon2_hasher() -> Argon2<'static> {
    let params = Params::new(
        ARGON2_MEMORY_KIB,
        ARGON2_ITERATIONS,
        ARGON2_PARALLELISM,
        None,
    )
    .expect("pinned Argon2 params are valid");
    Argon2::new(Algorithm::Argon2id, Version::V0x13, params)
}

/// Hash a password using Argon2id
pub fn hash_password(password: &str) -> Result<String> {
    // `password-hash` 0.6 generates the salt itself, from the OS CSPRNG via
    // `getrandom`, at the same 16-byte recommended length the explicit
    // `SaltString::generate(&mut OsRng)` call used before. Passing a salt is
    // still possible (`hash_password_with_salt`) but takes raw bytes and buys
    // nothing here, so the generated-salt form is the one to use.
    let hash: PasswordHash = argon2_hasher()
        .hash_password(password.as_bytes())
        .map_err(|e| anyhow::anyhow!("Failed to hash password: {}", e))?;

    Ok(hash.to_string())
}

/// Verify a password against a hash
pub fn verify_password(password: &str, hash: &str) -> Result<bool> {
    let parsed_hash = PasswordHash::new(hash)
        .map_err(|e| anyhow::anyhow!("Failed to parse password hash: {}", e))?;

    // Verification uses the cost params embedded in `parsed_hash`, so this also
    // verifies legacy hashes created with the previous (default) configuration.
    Ok(argon2_hasher()
        .verify_password(password.as_bytes(), &parsed_hash)
        .is_ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hash_and_verify() {
        let password = "my-secure-password-123!";
        let hash = hash_password(password).unwrap();

        // Verify correct password
        assert!(verify_password(password, &hash).unwrap());

        // Verify wrong password
        assert!(!verify_password("wrong-password", &hash).unwrap());
    }

    #[test]
    fn test_different_hashes() {
        let password = "same-password";
        let hash1 = hash_password(password).unwrap();
        let hash2 = hash_password(password).unwrap();

        // Same password should produce different hashes (different salts)
        assert_ne!(hash1, hash2);

        // But both should verify correctly
        assert!(verify_password(password, &hash1).unwrap());
        assert!(verify_password(password, &hash2).unwrap());
    }

    #[test]
    fn test_hash_format() {
        let hash = hash_password("test").unwrap();
        // Argon2id hash starts with $argon2id$
        assert!(hash.starts_with("$argon2id$"));
    }

    // Hashes generated by argon2 0.5.3 with the pinned parameters above, then
    // checked in. Every stored credential predating an `argon2` major bump is a
    // string of this shape, so this is the only test here that would catch an
    // upgrade that changes the encoding: the others hash and verify within one
    // version and would stay green even if `verify_password` lost the ability
    // to read older hashes.
    const ARGON2_0_5_GOLDEN_HASHES: &[(&str, &str)] = &[
        (
            "golden-argon2-0-5-password",
            "$argon2id$v=19$m=19456,t=2,p=1$5pBQVpgbHR9YLD4b0fxXog$AlsOVDAzD3ZcnnizNXlqAhkaCiizejDU6SX1SbAVGhQ",
        ),
        (
            "second-golden-password",
            "$argon2id$v=19$m=19456,t=2,p=1$uceDxlryPSgVt+jRVszCBA$5O0orNBhuvCS0hxCF+KJB5SLLgUy+PsVuuOPnDq9+7c",
        ),
    ];

    #[test]
    fn test_verifies_hashes_created_by_earlier_argon2_versions() {
        for (password, hash) in ARGON2_0_5_GOLDEN_HASHES {
            assert!(
                verify_password(password, hash).unwrap(),
                "stored argon2 0.5 hash must still verify: {hash}"
            );
            assert!(
                !verify_password("wrong-password", hash).unwrap(),
                "wrong password must not verify against: {hash}"
            );
        }
    }

    #[test]
    fn test_hash_uses_pinned_params() {
        // EVE-630: the encoded hash must carry the pinned cost parameters so a
        // dependency bump cannot silently change the work factor.
        let hash = hash_password("test").unwrap();
        assert!(
            hash.contains(&format!(
                "m={ARGON2_MEMORY_KIB},t={ARGON2_ITERATIONS},p={ARGON2_PARALLELISM}"
            )),
            "hash must encode pinned Argon2 params: {hash}"
        );
    }
}
